### ISSUE TITLE
Crossfade animation is dropping frames

### ISSUE THREAD

**Issue by AlvarezAriel** [android/compose-samples#10]
- **Device:** Samsung Galaxy S9+
 - **Sample:** Jetnews

When navigating from Home to Article screen (and from the Article back to the Home screen by clicking the back arrow button) the `Crossfade` transitions are dropping frames.

```kotlin
@Composable
private fun AppContent(openDrawer: () -> Unit) {
    Crossfade(JetnewsStatus.currentScreen) { screen ->
        Surface(color = +themeColor { background }) {
            when (screen) {
                is Screen.Home -> HomeScreen { openDrawer() }
                is Screen.Interests -> InterestsScreen { openDrawer() }
                is Screen.Article -> ArticleScreen(postId = screen.postId)
            }
        }
    }
}
```

**Comment by qianlvable** [comment]
too laggy this app

**Comment by nickbutcher** [comment]
Thank you for the report. Jetpack Compose is currently in Developer Preview and has not been heavily optimized for performance. Closing this issues.
