### ISSUE TITLE
[JetSurvey]: RadioButton parent should have selectableGroup modifier

### ISSUE THREAD

**Issue by JolandaVerhoef** [android/compose-samples#1023]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### Is this an issue related to one of the samples?

- [X] Yes, this is a specific issue related to this samples repo.

### Sample app

Jetsurvey

### What happened?

RadioButton parent should have selectableGroup modifier set to help TalkBack. Children with selectable modifier should have role set to RadioButton.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by IanGClifton** [comment]
Thanks for catching this! I can probably put up a PR next week.
