### ISSUE TITLE
[Jetchat] Testing TextField keyboard type

### ISSUE THREAD

**Issue by stanroy** [android/compose-samples#1027]
How would you go about testing what keyboard type TextField uses, for example in Jetchat I wanted to check if user input has an alphanumeric keyboard type. 

I can see that in SemanticProperties there is ImeAction, but I can't see anything I could use to check KeyboardOptions.

**Comment by JolandaVerhoef** [comment]
The `KeyboardOptions` aren't part of the semantics, as they are not used by accessibility services. Therefore, if you want to verify that the correct keyboard is showing, you could do this with a screenshot test. Alternatively, you could set a custom semantics property with this value, and verify that custom property in your test.
