### ISSUE TITLE
Feature

### ISSUE THREAD

**Issue by Leslala** [android/compose-samples#1030]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is this a feature request for one of the samples?

- [X] Yes, this is a specific request related to this samples repo.

### Sample app

Crane

### Describe the problem

I'm always frustrated when it won't work

### Describe the solution

Fix it

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by simona-anomis** [comment]
Apologies @Leslala, but there isn't enough information in this issue to understand what the problem is? Could you please provide more detailed information and open a new issue? Thanks!
