### ISSUE TITLE
Feautue[FR]: 

### ISSUE THREAD

**Issue by Leslala** [android/compose-samples#1031]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is this a feature request for one of the samples?

- [X] Yes, this is a specific request related to this samples repo.

### Sample app

Crane

### Describe the problem

I'm always frustrated when it won't work

### Describe the solution

Fix it

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by riggaroo** [comment]
Hi - this doesn't have enough detail as to what the feature request is. Closing this, please add more detail if you are missing something.
