### ISSUE TITLE
Not supporting to Dark and Dynamic Theme (as per Material3 guidelines)

### ISSUE THREAD

**Issue by hassaanjamil** [android/compose-samples#1037]
I have cloned the sample, the samples I have checked are working fine for light mode/theme but when I switched to dark theme and changed the dynamic colors to test if the application is reflecting the change or not, then some of its components were working for the case like Toast, etc. Adding modes will be of much help, I appreciated the work which has already been done, it is fantastic.

**Comment by riggaroo** [comment]
Hi @hassaanjamil Can you give more details of which samples and the exact issue you are experiencing? Some samples aren't designed to work with dynamic theming - so its not expected that all of them would work.
