### ISSUE TITLE
[JetSurvey]: Migrate to Compose navigation

### ISSUE THREAD

**Issue by antranvn** [android/compose-samples#1038]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is this a feature request for one of the samples?

- [X] Yes, this is a specific request related to this samples repo.

### Sample app

Jetsurvey

### Describe the problem

It is not Jetpack compose friendly, please migrate it to 100% Jetpack compose, without any XML file or fragment.

### Describe the solution

Use Jetpack Compose with Navigation Compose

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by IanGClifton** [comment]
I'm investigating this as part of simplifying JetSurvey as a sample. The current use of XML Navigation should be swapped out with Compose Navigation, but I also need to consider how to handle the survey screens themselves. Ideally these should properly handle back navigation and continue to animate nicely. I'll look at this a bit more in a few weeks.
