### ISSUE TITLE
[JetNews]: InterestsScreen item clicking crash

### ISSUE THREAD

**Issue by halilozcan** [android/compose-samples#1042]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### Is this an issue related to one of the samples?

- [X] Yes, this is a specific issue related to this samples repo.

### Sample app

JetNews

### What happened?

When I click any item (topic, people and publication) on Interest Screen the app crashes because of initial state (emptySet).

### Relevant logcat output

```shell
Process: com.example.jetnews, PID: 14780
                                                                                                    java.lang.ClassCastException: kotlin.collections.EmptySet cannot be cast to kotlin.collections.MutableSet
                                                                                                    	at com.example.jetnews.utils.MapExtensionsKt.addOrRemove(MapExtensions.kt:20)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by astamato** [comment]
Should fix https://github.com/android/compose-samples/issues/1042

**Comment by riggaroo** [comment]
thanks for the fix!
