### ISSUE TITLE
[FR]: 

### ISSUE THREAD

**Issue by 594238813** [android/compose-samples#1043]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is this a feature request for one of the samples?

- [X] Yes, this is a specific request related to this samples repo.

### Sample app

Other (bug not related to sample app)

### Describe the problem

I want to set the saturation in compose （Text, ...） 

in android.view.View package
```
mGrayMatrix.setSaturation(saturation)
mGrayPaint.colorFilter = ColorMatrixColorFilter(mGrayMatrix)
view.setLayerType(View.LAYER_TYPE_HARDWARE, mGrayPaint)
```

in compose 
```
otherLayout()
Canvas(modifier = Modifier.fillMaxSize()   ){
    drawRect(
        color = Color.White,
        blendMode = BlendMode.Saturation
    )
}
```
but  `BlendMode`  Added in [API level 29](https://developer.android.google.cn/guide/topics/manifest/uses-sdk-element.html#ApiLevels)
so  28-   ？    (28  write  screen)
i need help

### Describe the solution

replace all  Color？

i need help

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by IanGClifton** [comment]
Hello, it looks like this issue isn't specific to the samples in this repository. I'd recommend posting this question to StackOverflow to get a wider audience.
