### ISSUE TITLE
In many views the preview code isn't implemented

### ISSUE THREAD

**Issue by JohnFarl** [android/compose-samples#1089]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is this a feature request for one of the samples?

- [X] Yes, this is a specific request related to this samples repo.

### Sample app

Crane

### Describe the problem

This is official Jetpack Compose samples repository so people expect it show how Jetpack Compose simplify the UI development, but, unfortunately, I have seen that in most views the `@Preview` section is missing, and it isn't easy to add, because seems are missing trivial ways to make preview to work when are involved modifiers, hilt models etc.  to pass as parameter of various Composable functions
 
This forces to launch emulator every time to see the effect of every change and makes the Compose and so called MAD experience very unpleasant compared to XML.

### Describe the solution

Add a proper implementation to make preview work for every view not just few elements.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by IanGClifton** [comment]
Assigning to Rebecca for Crane.

@JohnFarl are there any specific screens or components you'd expect to see previews for?

**Comment by JohnFarl** [comment]
@IanGClifton 

I expect to have preview in every view, especially the main ones, to have a practical way to see how UI design is progressing and if I'm getting the visual experience desired, without the need to re-run whole App continuously. 

e.g. I have tested Crane sample and there isn't any preview for any view with the only exception of these little elements `CraneDrawer.kt` and `CraneBaseUserInput.kt`, this means that to see how various areas of app actually looks it is needed to rely entirely Emulator, with a launch after every edit to to see the result of every change.
