### ISSUE TITLE
How do I preview icons while using them？

### ISSUE THREAD

**Issue by 549865602** [android/compose-samples#1091]
Like i said , i agree that Compose Icon is a very convenient feature but i can not find a visible way to preview how icons look like.Pls tell me if i am wrong . Or the visible way is required.

**Comment by wamiikechukwu** [comment]
Yes! I also experience the same issue unfortunately. What i do is to use icons from material design libarary, wrap them in a composable and then preview them. Its more work. I know but it gets the work done.

**Comment by riggaroo** [comment]
What @wamiikechukwu has described is the only way currently. Please note this issue tracker should be used for issues with the samples and not general Compose questions, for that we advise StackOverflow or the official issue tracker https://b.corp.google.com/issues/new?component=856989&template=1425922
