### ISSUE TITLE
Toolbar - navigation button hardly clickable

### ISSUE THREAD

**Issue by mice777** [android/compose-samples#11]
The button in top Toolbar is very hardly clickable. It uses size of drawable for click area, which is 24x24 dp for ic_back.xml. 48dp is probably recommended minimum for buttons.

Ideally the button uses entire toolbar height, and has predefined width, starting from leftmost pixels. The drawable icon may be whatever size it wishes, but clickable area should be large enough. 

See visualization of current clickable area:
![image](https://user-images.githubusercontent.com/3145438/67989513-53255d00-fc33-11e9-8d76-b5e476bb06da.png)

**Comment by rock3r** [comment]
This was fixed by #45 // CC @nickbutcher

**Comment by JoseAlcerreca** [comment]
This has been fixed
