### ISSUE TITLE
I want an example of LinearProgressIndicator

### ISSUE THREAD

**Issue by nieaowei** [android/compose-samples#110]
I searched for a long time, but I couldn't find relevant examples. I don't know how to dynamically modify the progress bar.

**Comment by nickbutcher** [comment]
Demos here: https://cs.android.com/androidx/platform/frameworks/support/+/androidx-master-dev:ui/ui-material/integration-tests/material-demos/src/main/java/androidx/ui/material/demos/ProgressIndicatorDemo.kt

To control the progress, use the `progress` paramerer: https://cs.android.com/androidx/platform/frameworks/support/+/androidx-master-dev:ui/ui-material/src/main/java/androidx/ui/material/ProgressIndicator.kt;l=62
