### ISSUE TITLE
Is the Reply app still in development?

### ISSUE THREAD

**Issue by RivanParmar** [android/compose-samples#1104]
Is the Reply app still under development or has it been abandoned? If it's still under development, then I would like to contribute to it! So is there any public roadmap available for it?

**Comment by arriolac** [comment]
Yes! Reply is still active and has not been abandoned. Contributions are welcome. See https://github.com/android/compose-samples/blob/main/CONTRIBUTING.md for more

**Comment by RivanParmar** [comment]
Is there any design file available for reference?
