### ISSUE TITLE
[FR]: Sharing common test code needs to be revisited

### ISSUE THREAD

**Issue by illarionov** [android/compose-samples#1105]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is this a feature request for one of the samples?

- [X] Yes, this is a specific request related to this samples repo.

### Sample app

Other (bug not related to sample app)

### Describe the problem

Some sample applications currently uses so-called "sharedTest" pattern to share test code between unit and instrumented tests. It is implemented by adding the same shared directory to different source sets: [JetNews](https://github.com/android/compose-samples/blob/450fec62750269e8ea84163bd67a9463a1e7dfb2/Owl/app/build.gradle.kts#LL65C36-L65C36), [Reply](https://github.com/android/compose-samples/blob/450fec62750269e8ea84163bd67a9463a1e7dfb2/Reply/app/build.gradle.kts#LL65C10-L65C10), [JetNews](https://github.com/android/compose-samples/blob/450fec62750269e8ea84163bd67a9463a1e7dfb2/JetNews/app/build.gradle.kts#L66)

Unfortunately this approach is no longer supported as of Android Gradle Plugin 7.2.0.  When opening an application in the recent versions of Android Studio, a warning appears:
```
Duplicate content roots detected.
Path [compose-samples/JetNews/app/src/sharedTest/java] of module [JetNews.app.unitTest]
was removed from modules [JetNews.app.androidTest]".
```
Although this warning does not affect the build, it may confuse readers and it can also lead to the use of unsupported practices in users projects.
Related issues:
https://issuetracker.google.com/issues/232420188#comment5
https://issuetracker.google.com/issues/232007221#comment17
https://github.com/robolectric/robolectric/issues/7432

### Describe the solution

The links above suggest creating separate modules for the common test code.
Also, since test sharing is not the main purpose of this repository, it may be worth considering to remove code sharing and keep only instrumented or unit tests.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by illarionov** [comment]
I notice that a similar problem has already been fixed in the `architecture-samples` repository: https://github.com/android/architecture-samples/issues/910

**Comment by rishiraj88** [comment]
Thanks, @illarionov
