### ISSUE TITLE
[FR]: Update AGP version to 8.0.0 after Android Studio Flamingo release

### ISSUE THREAD

**Issue by obask** [android/compose-samples#1111]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is this a feature request for one of the samples?

- [X] Yes, this is a specific request related to this samples repo.

### Sample app

Crane

### Describe the problem

Flamingo uses AGP 8.0.0 so it will ask users to update from 7.4.3, but it's not able to do handle project versions with BOM: https://issuetracker.google.com/issues/277261312

PS it make sense to wait for some time to let users upgrade from Electric Eel since it doesn't understand projects with 8.0.0

### Describe the solution

Use AGP Upgrade Assistant with Android Studio Giraffe to upgrade all samples to a new version.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by astamato** [comment]
I think this is addressed by this PR here https://github.com/android/compose-samples/pull/1114

**Comment by obask** [comment]
Closing, since the corresponding commit with a change have been merged
