### ISSUE TITLE
[FR]: Preferene UI example

### ISSUE THREAD

**Issue by otomir23** [android/compose-samples#1112]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is this a feature request for one of the samples?

- [X] Yes, this is a specific request related to this samples repo.

### Sample app

Other (bug not related to sample app)

### Describe the problem

There isn't a single sample app that shows how to implement prefernce/settings UI, which is very essential to even small scale apps. There are different preference libraries (androidx.preference, etc) and ways to implement the UI, so showing and official and recommended way to do this would be very nice.

### Describe the solution

Add preference screen to at least one of the sample apps. Preferably demonstrate all popular types of preference elements (toggle, select, custom value input) and show examples of common preference implementations (dark/light theme override, notifications, about this app).

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by riggaroo** [comment]
Hi @otomir23 - There is a preference /setting dialog in Now in Android Sample that showcases how to do a theme selector/override dark/light theme option. https://github.com/android/nowinandroid

**Comment by otomir23** [comment]
I'll check it out, thanks!
