### ISSUE TITLE
Code coverage support (Jacoco)

### ISSUE THREAD

**Issue by pajatopmr** [android/compose-samples#113]
I have added support for generating a Jacoco code coverage report to the dev15 Jetnews sample code.

This contribution has been generated at the suggestion of Romain Guy, whom I wrongly credited for the astute addition of actual instrumentation tests in Jetnews. If this code, or a variant of it, is accepted, I will gladly add more tests to both increase the test coverage and, more importantly, reveal possible new problems with Jacoco as a result of Compose code generation.

The base support changes are essentially limited to `.../JetNews/build.gradle` and `.../JetNews/app/build.gradle` such that a code coverage report for Jetnews can be obtained by using `index.html` in the (Gradle default) directory `.../JetNews/app/build/reports/jacocoTestReport/html/`.

**Comment by JoseAlcerreca** [comment]
I don't think code coverage reports for UI tests is that relevant to be honest... in any case this is an issue, if you want to contribute with code open a pull request.
