### ISSUE TITLE
Preview isn't Working after Kotlin 1.4 bump.

### ISSUE THREAD

**Issue by handstandsam** [android/compose-samples#114]
Preview isn't working.  It was working with Kotlin 1.3.72 and compose 14, but the bumps (while the code works & launches), then Android Studio previews now fail.

Commit with changes: https://github.com/android/compose-samples/commit/90e3fb07f27f9d7b6b58de75af458cf9ed805af3

Android Studio 4.2 Canary 7

<img width="1440" alt="Screen Shot 2020-08-02 at 9 37 32 PM" src="https://user-images.githubusercontent.com/264948/89138586-14963900-d50a-11ea-8089-afb2b7fb30ad.png">

<img width="537" alt="Screen Shot 2020-08-02 at 9 39 40 PM" src="https://user-images.githubusercontent.com/264948/89138581-106a1b80-d50a-11ea-8db2-b46e54a4f1c3.png">

**Comment by nickbutcher** [comment]
Unfortunately this is a known issue and is awaiting a fix in Studio to support Kotlin 1.4 in previews. I'll leave this open in case folks want to follow and close once resolved.

**Comment by oh-eRin** [comment]
I have the same problem. Can i return dev15 to dev14 to resolve this error?

**Comment by nickbutcher** [comment]
That should work. You can also follow along here: https://issuetracker.google.com/issues/162000445

**Comment by JoseAlcerreca** [comment]
Previews are back!
