### ISSUE TITLE
[Bug]: Unresolved reference: libs

### ISSUE THREAD

**Issue by theGeekyLad** [android/compose-samples#1147]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### Is this an issue related to one of the samples?

- [X] Yes, this is a specific issue related to this samples repo.

### Sample app

Other (bug not related to sample app)

### What happened?

I get the `Unresolved reference: libs` error while trying to perform a Gradle build. Looks like a bunch of `libs. ...` are used within the `build.gradle.kts` file but I don't see the definition of these `libs` variables.

Any thoughts?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bentrengrove** [comment]
libs is the gradle version catalog generated by gradle. What version of Android Studio are you using and how are you trying to build the samples? I can't reproduce any issues, the project seems to build fine.

**Comment by DavidFaermanPendo** [comment]
i get
Build file '.../compose-samples/JetNews/app/build.gradle.kts' line: 17

Error resolving plugin [id: 'com.android.application', version: '8.0.2']
> The request for this plugin could not be satisfied because the plugin is already on the classpath with an unknown version, so compatibility cannot be checked.

**Comment by zeeshanali-k** [comment]
Make sure that gradle 8.1 is downloaded and file name "libs.versions.toml" exists under module level gradle folder of JetNews project

**Comment by OkuiohSd** [comment]
https://qrco.de/bdCPfc

**Comment by joyceHong0524** [comment]
I set android gradle plugin version 8.0.2
gradle version 8.1

still getting an error like this

org.gradle.api.GradleException: Error resolving plugin [id: 'com.android.application', version: '8.0.2']

**Comment by joyceHong0524** [comment]
So this is how I fixed the issue,

1. libs.versions.toml change androidGradlePlugin, android-application  like this.
[versions]
androidGradlePlugin = "8.0.2"
[plugins]
android-application = { id = "com.android.application", version = "8.0.2" }

2. At Project build.gradle.kts, add these lines in plugins {}

plugins {
    alias(libs.plugins.gradle.versions)
    alias(libs.plugins.version.catalog.update)
   // these lines.. 
    alias(libs.plugins.kotlin.android) apply false
    alias(libs.plugins.kapt) apply false
    alias(libs.plugins.hilt) apply false
    alias(libs.plugins.secrets) apply false
    alias(libs.plugins.android.application) apply false
    alias(libs.plugins.android.test) apply false
}

and it started to work.

**Comment by octoberv29** [comment]
a simpler way to solve it for me was:
1. create a new Kotlin Multiplatform project in Android Studio
2. copy the `libs.versions.toml` file over to your project
3. copy the `build.gradle.kts` (project level) over to your project or just copy the libs you need to add

**Comment by AndroidDeveloper333** [comment]
try to clean cache Android Studio

**Comment by imba-tjd** [comment]
I encountered this. It turns out I deleted the `<project>/gradle` folder, because I wanted to use global gradle. (I have never used gradle before but I had experience with maven.)
