### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by jmmmg** [android/compose-samples#1160]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### Is this an issue related to one of the samples?

- [X] Yes, this is a specific issue related to this samples repo.

### Sample app

JetNews

### What happened?

A bug happened!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by IanGClifton** [comment]
This issue doesn't mention anything specific. If there's a bug you'd like to report, please include some details.
