### ISSUE TITLE
[Bug]: I'm unable to pull a request against main or push a new branch even after signing CLA

### ISSUE THREAD

**Issue by hiftikha** [android/compose-samples#1171]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### Is this an issue related to one of the samples?

- [X] Yes, this is a specific issue related to this samples repo.

### Sample app

Other (bug not related to sample app)

### What happened?

What am I doing wrong? I've tried checking my credentials and SSH key auth

### Relevant logcat output

```shell
remote: Permission to android/compose-samples.git denied to hiftikha.
fatal: unable to access 'https://github.com/android/compose-samples.git/': The requested URL returned error: 403
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JolandaVerhoef** [comment]
Hi there! We work according to the GitHub Standard Fork & Pull Request Workflow, which means you will have to create a fork and then a PR from that fork. See https://gist.github.com/Chaser324/ce0505fbed06b947d962

**Comment by hiftikha** [comment]
Sweet will do! Thanks!
