### ISSUE TITLE
[Bug]: AppTest

### ISSUE THREAD

**Issue by rincemermaid** [android/compose-samples#1188]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### Is this an issue related to one of the samples?

- [X] Yes, this is a specific issue related to this samples repo.

### Sample app

Jetsnack

### What happened?

The createAndroidComposeRule  function is marked as an unresolved reference for the androidTest when I open the app in Android Studios

<img width="753" alt="image" src="https://github.com/android/compose-samples/assets/65420367/a33a0ba6-fafb-4952-b7ce-3c4ec5045a5f">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rishiraj88** [comment]
@rincemermaid , your `junit4` itself is not imported well. Please check if the relevant dependencies are listed well and refresh your project dependency download/inclusion for visibility.

**Comment by rincemermaid** [comment]
> @rincemermaid , your `junit4` itself is not imported well. Please check if the relevant dependencies are listed well and refresh your project dependency download/inclusion for visibility.

How do I import junit4 in the project dependecncy
