### ISSUE TITLE
[Bug]:      should  viewModelScope.launch{} correct into iewModelScope.launch(Dispatchers.IO)  {} or not ?

### ISSUE THREAD

**Issue by clarkshu1016** [android/compose-samples#1198]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### Is this an issue related to one of the samples?

- [X] Yes, this is a specific issue related to this samples repo.

### Sample app

JetNews

### What happened?

https://github.com/android/compose-samples/blob/b7fab5cacac879351b8b37ff6cc674398805215d/JetNews/app/src/main/java/com/example/jetnews/ui/home/HomeViewModel.kt#L161

default viewModelScope.launch running on the main thread.
       val result = postsRepository.getPostsFeed()
may take long time, why not put viewModelScope.launch into Dispathers.IO?

### Relevant logcat output

```shell
viewModelScope.launch(Dispatchers.IO) {
            val result = postsRepository.getPostsFeed()
            viewModelState.update {
                when (result) {
                    is Result.Success -> it.copy(postsFeed = result.data, isLoading = false)
                    is Result.Error -> {
                        val errorMessages = it.errorMessages + ErrorMessage(
                            id = UUID.randomUUID().mostSignificantBits,
                            messageId = R.string.load_error
                        )
                        it.copy(errorMessages = errorMessages, isLoading = false)
                    }
                }
            }
        }
    }
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bentrengrove** [comment]
The general pattern we recommend is to launch your coroutines in`viewModelScope` on the main thread and then use `withContext` to switch to a background thread when needed. This keeps your view model clean and allows mutating your view model state back on the main thread once the result is returned.

If you have a look at the implementation of `getPostsFeed()` you will see it uses this pattern and switches to a background thread. The coroutine in the view model automatically waits for this result, but does so without blocking the main thread thanks to the way coroutines suspend. Once the result is returned, the coroutine automatically continues execution and updates our view model state.

```
override suspend fun getPostsFeed(): Result<PostsFeed> {
        return withContext(Dispatchers.IO) {
            delay(800) // pretend we're on a slow network
            if (shouldRandomlyFail()) {
                Result.Error(IllegalStateException())
            } else {
                postsFeed.update { posts }
                Result.Success(posts)
            }
        }
    }
```
