### ISSUE TITLE
[FR]: deprecate ConstraintLayout

### ISSUE THREAD

**Issue by anlexN** [android/compose-samples#1204]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is this a feature request for one of the samples?

- [X] Yes, this is a specific request related to this samples repo.

### Sample app

Owl

### Describe the problem

Based on [ConstraintLayout in Compose](https://developer.android.com/jetpack/compose/layouts/constraintlayout)

In the View system, `ConstraintLayout` was the recommended way to create large and complex layouts, as a flat view hierarchy was better for performance than nested views are. However, this is not a concern in Compose, which is able to efficiently handle deep layout hierarchies.

**Guidelines**
Note: Consider using the `Spacer` composable to achieve a similar effect with `Rows` and `Columns`.

**Barriers**
Note: Consider using [Intrinsic measurements](https://developer.android.com/jetpack/compose/layouts/intrinsic-measurements) to achieve a similar effect with Rows and Columns.

**Chains**
Note: Consider using traditional Rows and Columns with different [Arrangements](https://developer.android.com/reference/kotlin/androidx/compose/foundation/layout/Arrangement) to achieve a similar effect to Chains in ConstraintLayout.

> But [some samples](https://github.com/search?q=repo%3Aandroid%2Fcompose-samples+ConstraintLayout&type=code) still use `ConstraintLayout`, You didn't fulfill your promise: **BEST PRATICE**

### Describe the solution

WE can only use `Spacer`, `Rows`, `Columns`, `Intrinsic measurements`, `Arrangements`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by riggaroo** [comment]
Thanks for your issue. Whilst our documentation shows alternatives to take instead of using ConstraintLayout, ConstraintLayout is still a valid approach to achieving certain UIs. The samples in this repo aim to demonstrate different API usages, and as such some will use ConstraintLayout. 
Hope this helps!

**Comment by anlexN** [comment]
**It's wrong.**

you now practice confuse many and many people. For example, my company have 100 engineers, 87 engineers are misdirected.

I have read docs step by step, docs say `compose-samples` demonstate best pratices.

ConstraintLayout may be a valid approach, but not best pratice.

`A is A, A is not B`

OK? You didn't fulfill your promise
