### ISSUE TITLE
[FR]: Markdown support

### ISSUE THREAD

**Issue by TinaT2** [android/compose-samples#1211]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is this a feature request for one of the samples?

- [X] Yes, this is a specific request related to this samples repo.

### Sample app

Jetchat

### Describe the problem

I've used some libraries to support markdown in compose like Rich text. All had the same issue: unable to measure measurables using onTextLayout.

### Describe the solution

If compose has its own markdown we can better develop a chat application with the coordination of markdown and Flexbox for the layout.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bentrengrove** [comment]
Hello, this request does not relate to the samples but seems to be a specific request for Compose in general.
I will close this issue out but please search for an existing issue or file the request at goo.gle/compose-feedback
