### ISSUE TITLE
[Bug]: [libhwui.so] SkSurface::getCanvas()

### ISSUE THREAD

**Issue by appinion-dev** [android/compose-samples#1229]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### Is this an issue related to one of the samples?

- [X] Yes, this is a specific issue related to this samples repo.

### Sample app

Other (bug not related to sample app)

### What happened?

[libhwui.so] SkSurface::getCanvas()

### Relevant logcat output

```shell
backtrace:
  #00  pc 0x0000000000691b28  /system/lib64/libhwui.so (SkSurface::getCanvas()+16)
  #01  pc 0x00000000001da854  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::GLFunctorDrawable::onDraw(SkCanvas*)+1228)
  #02  pc 0x00000000005ab690  /system/lib64/libhwui.so (SkDrawable::draw(SkCanvas*, SkMatrix const*)+352)
  #03  pc 0x00000000005ac4cc  /system/lib64/libhwui.so (SkLiteDL::draw(SkCanvas*) const+196)
  #04  pc 0x000000000058dbb4  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const+292)
  #05  pc 0x000000000058df7c  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::forceDraw(SkCanvas*)+252)
  #06  pc 0x00000000005ab5c4  /system/lib64/libhwui.so (SkDrawable::draw(SkCanvas*, SkMatrix const*)+148)
  #07  pc 0x00000000005ac4cc  /system/lib64/libhwui.so (SkLiteDL::draw(SkCanvas*) const+196)
  #08  pc 0x000000000058dbb4  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const+292)
  #09  pc 0x000000000058df7c  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::forceDraw(SkCanvas*)+252)
  #10  pc 0x00000000005ab5c4  /system/lib64/libhwui.so (SkDrawable::draw(SkCanvas*, SkMatrix const*)+148)
  #11  pc 0x00000000005ac4cc  /system/lib64/libhwui.so (SkLiteDL::draw(SkCanvas*) const+196)
  #12  pc 0x000000000058dbb4  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const+292)
  #13  pc 0x000000000058df7c  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::forceDraw(SkCanvas*)+252)
  #14  pc 0x00000000005ab5c4  /system/lib64/libhwui.so (SkDrawable::draw(SkCanvas*, SkMatrix const*)+148)
  #15  pc 0x00000000005ac4cc  /system/lib64/libhwui.so (SkLiteDL::draw(SkCanvas*) const+196)
  #16  pc 0x000000000058dbb4  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const+292)
  #17  pc 0x000000000058df7c  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::forceDraw(SkCanvas*)+252)
  #18  pc 0x00000000005ab5c4  /system/lib64/libhwui.so (SkDrawable::draw(SkCanvas*, SkMatrix const*)+148)
  #19  pc 0x00000000005ac4cc  /system/lib64/libhwui.so (SkLiteDL::draw(SkCanvas*) const+196)
  #20  pc 0x000000000058dbb4  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const+292)
  #21  pc 0x000000000058df7c  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::forceDraw(SkCanvas*)+252)
  #22  pc 0x00000000001e3d20  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::SkiaPipeline::renderLayersImpl(android::uirenderer::LayerUpdateQueue const&, bool, bool)+752)
  #23  pc 0x00000000005d1b18  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::SkiaPipeline::renderFrame(android::uirenderer::LayerUpdateQueue const&, SkRect const&, std::__1::vector<android::sp<android::uirenderer::RenderNode>, std::__1::allocator<android::sp<android::uirenderer::RenderNode>>> const&, bool, bool, android::uirenderer::Rect const&, sk_sp<SkSurface>)+96)
  #24  pc 0x00000000001e1e7c  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::SkiaOpenGLPipeline::draw(android::uirenderer::renderthread::Frame const&, SkRect const&, SkRect const&, android::uirenderer::FrameBuilder::LightGeometry const&, android::uirenderer::LayerUpdateQueue*, android::uirenderer::Rect const&, bool, bool, android::uirenderer::BakedOpRenderer::LightInfo const&, std::__1::vector<android::sp<android::uirenderer::RenderNode>, std::__1::allocator<android::sp<android::uirenderer::Re    #25 pc 00000000001ef818  /system/lib64/libhwui.so (android::uirenderer::renderthread::CanvasContext::draw()+320)
  #25  pc 0x00000000005d5af4  /system/lib64/libhwui.so (_ZNSt3__110__function6__funcIZN7android10uirenderer12renderthread13DrawFrameTask11postAndWaitEvE3$_0NS_9allocatorIS6_EEFvvEEclEv$c303f2d2360db58ed70a2d0ac7ed911b+644)
  #26  pc 0x000000000058cba8  /system/lib64/libhwui.so (android::uirenderer::WorkQueue::process()+168)
  #27  pc 0x00000000001fe0a4  /system/lib64/libhwui.so (android::uirenderer::renderthread::RenderThread::threadLoop()+244)
  #28  pc 0x000000000000fc08  /system/lib64/libutils.so (android::Thread::_threadLoop(void*)+280)
  #29  pc 0x0000000000084ce4  /system/lib64/libc.so (__pthread_start(void*)+36)
  #30  pc 0x000000000002344c  /system/lib64/libc.so (__start_thread+68)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bentrengrove** [comment]
Thanks for the report

Do you have any more info on it? What sample did it occur in and any instructions to reproduce?

**Comment by StanislavChumarin** [comment]
I have same issue on **production** App. This happens 100% on Samsung (o1s, b4q, y2q, r8q, r9q, b0q.......) Android 13. 
Compose version 1.4.3
androidx.compose.ui:ui:1.3.3
androidx.compose.foundation:foundation:1.3.1
androidx.compose.material:material:1.3.1

backtrace:
  #00  pc 0x00000000006a4010  /system/lib64/libhwui.so (SkSurface::getCanvas()+20)
  #01  pc 0x000000000051c398  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::GLFunctorDrawable::onDraw(SkCanvas*)+864)
  #02  pc 0x00000000005ade4c  /system/lib64/libhwui.so (SkDrawable::draw(SkCanvas*, SkMatrix const*)+120)
  #03  pc 0x00000000008f1958  /system/lib64/libhwui.so (skgpu::v1::Device::drawDrawable(SkCanvas*, SkDrawable*, SkMatrix const*)+348)
  #04  pc 0x00000000004faa38  /system/lib64/libhwui.so (android::uirenderer::$_37::__invoke(void const*, SkCanvas*, SkMatrix const&)+140)
  #05  pc 0x00000000004f7a00  /system/lib64/libhwui.so (android::uirenderer::DisplayListData::draw(SkCanvas*) const+132)
  #06  pc 0x00000000004e0538  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const+1752)
  #07  pc 0x00000000004e0c74  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::forceDraw(SkCanvas*) const+292)
  #08  pc 0x00000000005ade4c  /system/lib64/libhwui.so (SkDrawable::draw(SkCanvas*, SkMatrix const*)+120)
  #09  pc 0x00000000004f7a00  /system/lib64/libhwui.so (android::uirenderer::DisplayListData::draw(SkCanvas*) const+132)
  #10  pc 0x00000000004e0538  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const+1752)
  #11  pc 0x00000000004e0c74  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::forceDraw(SkCanvas*) const+292)
  #12  pc 0x00000000005ade4c  /system/lib64/libhwui.so (SkDrawable::draw(SkCanvas*, SkMatrix const*)+120)
  #13  pc 0x00000000004f7a00  /system/lib64/libhwui.so (android::uirenderer::DisplayListData::draw(SkCanvas*) const+132)
  #14  pc 0x00000000004e0538  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const+1752)
  #15  pc 0x00000000004e0c74  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::forceDraw(SkCanvas*) const+292)
  #16  pc 0x00000000005ade4c  /system/lib64/libhwui.so (SkDrawable::draw(SkCanvas*, SkMatrix const*)+120)
  #17  pc 0x00000000004f7a00  /system/lib64/libhwui.so (android::uirenderer::DisplayListData::draw(SkCanvas*) const+132)
  #18  pc 0x00000000004e0538  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const+1752)
  #19  pc 0x00000000004e0c74  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::forceDraw(SkCanvas*) const+292)
  #20  pc 0x00000000005ade4c  /system/lib64/libhwui.so (SkDrawable::draw(SkCanvas*, SkMatrix const*)+120)
  #21  pc 0x00000000004f7a00  /system/lib64/libhwui.so (android::uirenderer::DisplayListData::draw(SkCanvas*) const+132)
  #22  pc 0x00000000004e0538  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const+1752)
  #23  pc 0x00000000004e0c74  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::forceDraw(SkCanvas*) const+292)
  #24  pc 0x0000000000521b1c  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::SkiaPipeline::renderLayersImpl(android::uirenderer::LayerUpdateQueue const&, bool)+492)
  #25  pc 0x0000000000522df4  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::SkiaPipeline::renderFrame(android::uirenderer::LayerUpdateQueue const&, SkRect const&, std::__1::vector<android::sp<android::uirenderer::RenderNode>, std::__1::allocator<android::sp<android::uirenderer::RenderNode> > > const&, bool, android::uirenderer::Rect const&, sk_sp<SkSurface>, SkMatrix const&)+608)
  #26  pc 0x0000000000520ad8  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::SkiaOpenGLPipeline::draw(android::uirenderer::renderthread::Frame const&, SkRect const&, SkRect const&, android::uirenderer::LightGeometry const&, android::uirenderer::LayerUpdateQueue*, android::uirenderer::Rect const&, bool, android::uirenderer::LightInfo const&, std::__1::vector<android::sp<android::uirenderer::RenderNode>, std::__1::allocator<android::sp<android::uirenderer::RenderNode> > > const&, android::uirenderer::FrameInfoVisualizer*)+520)
  #27  pc 0x0000000000528550  /system/lib64/libhwui.so (android::uirenderer::renderthread::CanvasContext::draw()+1368)
  #28  pc 0x000000000052b04c  /system/lib64/libhwui.so (std::__1::__function::__func<android::uirenderer::renderthread::DrawFrameTask::postAndWait()::$_0, std::__1::allocator<android::uirenderer::renderthread::DrawFrameTask::postAndWait()::$_0>, void ()>::operator()() (.c1671e787f244890c877724752face20)+888)
  #29  pc 0x000000000051a844  /system/lib64/libhwui.so (android::uirenderer::WorkQueue::process()+588)
  #30  pc 0x000000000053b948  /system/lib64/libhwui.so (android::uirenderer::renderthread::RenderThread::threadLoop()+416)
  #31  pc 0x0000000000013418  /system/lib64/libutils.so (android::Thread::_threadLoop(void*)+424)
  #32  pc 0x00000000000bb6e8  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+208)
  #33  pc 0x0000000000054fdc  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+68)
