### ISSUE TITLE
[FR]: Yellow Background Element for Below Android 13

### ISSUE THREAD

**Issue by ibrahim4851** [android/compose-samples#1250]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is this a feature request for one of the samples?

- [X] Yes, this is a specific request related to this samples repo.

### Sample app

Other (bug not related to sample app)

### Describe the problem

In Android 13 or above, we can see that the wawing effect that is created with AGSL is working. But below Android 13, it's just a gradient. 

### Describe the solution

I would like to translate the AGSL code to GLSL code and apply it to the else block here:

```
fun Modifier.yellowBackground(): Modifier =
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
        this.then(YellowBackgroundElement)
    } else {
        drawWithCache {

            val gradientBrush = Brush.verticalGradient(listOf(Yellow, YellowVariant, White))
            onDrawBehind {
                drawRect(gradientBrush)
            }
       
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by IanGClifton** [comment]
Is there a clean way of applying an OpenGL shader to a modifier? If so, that'd be awesome! I could see a path using the AndroidExternalSurface composable, but that wouldn't be as clean in the hierarchy.

(Also adding Riggaroo, since I only wrote the shader and she did everything else).

**Comment by ibrahim4851** [comment]
I've found this repo that renders GLSL shaders on Jetpack Compose but seems like he uses AndroidView for this.

[](https://github.com/thelumiereguy/ShaderShowcaseApp)

**Comment by IanGClifton** [comment]
If we have to rely on an AndroidView underneath, I'd prefer to use AndroidExternalSurface as an official solution, but I don't see a path to using that within a modifier.

**Comment by riggaroo** [comment]
Yeah an AndroidExternalSurface with all the same setup is the other approach, this approach done for this example is a bit different, however it wont be as simple to setup. AGSL is only available from Android 13+.
