### ISSUE TITLE
[FR]: Jetchat is not laid out edge-to-edge in 2 & 3-button navigation mode

### ISSUE THREAD

**Issue by manabu-nakamura** [android/compose-samples#1256]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is this a feature request for one of the samples?

- [X] Yes, this is a specific request related to this samples repo.

### Sample app

Jetchat

### Describe the problem

Jetchat is not laid out edge-to-edge in 2 & 3-button navigation mode (it is not drawn behind the system navigation bar in 2 & 3-button navigation mode).
![Screenshot_20240213_232305](https://github.com/android/compose-samples/assets/71050561/619c2966-3b9d-4ef8-a3d2-d414722d7352)

### Describe the solution

Jetchat is laid out edge-to-edge in 2 & 3-button navigation mode (it is drawn behind the system navigation bar in 2 & 3-button navigation mode).
![Screenshot_20240213_232354](https://github.com/android/compose-samples/assets/71050561/23441f33-b68a-4bd7-b42d-d7218221eedd)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sothsokna** [comment]
Needs  help
