### ISSUE TITLE
[Bug]:  JNews swipe to cancel recording is not working, pointerToDetectGesture is not working as expected.

### ISSUE THREAD

**Issue by shubham8360** [android/compose-samples#1281]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### Is this an issue related to one of the samples?

- [X] Yes, this is a specific issue related to this samples repo.

### Sample app

JetNews

### What happened?

After updating android bom compose bersion to latest one as use in Jnews, I am unable to use Swipe to cancel of recording , as Swipe to cancel is not working as expected.
Previous android compose bom version="2023.10.01" to  "2024.02.02" unable to use swipe to cancel for recording

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cryptrr** [comment]
This bug is in Jetchat too.

```
this.detectDragGesturesAfterLongPress(
            onDragStart = {
                logger.d{"onDragStart"}
                onSwipeProgressChanged(0f)
                offsetY = 0f
                dragging = true
                onStartRecording()
            },
            onDragCancel = {
                logger.d{"onDragCancel , ${horizontalSwipeProgress()}"}

                onCancelRecording()
                dragging = false
            },
            onDragEnd = {
                logger.d{"onDragEnd"}

                if (dragging) {
                    onFinishRecording()
                }
                dragging = false
            },
            onDrag = { change, dragAmount ->
                logger.d{"onDrag"}
                if (dragging) {
                    onSwipeProgressChanged(horizontalSwipeProgress() + dragAmount.x)
                    offsetY += dragAmount.y
                    val offsetX = horizontalSwipeProgress()
                    if (
                        offsetX < 0 &&
                        abs(offsetX) >= swipeToCancelThresholdPx &&
                        abs(offsetY) <= verticalThresholdPx
                    ) {
                        onCancelRecording()
                        dragging = false
                    }
                }
            }
        )
```

Whether you "swipe to cancel recording" or "end the drag by taking your finger off the button" , in both these cases only `onDragCanceled` is called .

`onDragEnd` and `onDrag` functions are not called at all.

I am using Compose Multiplatform 1.6.0

**Comment by shubham8360** [comment]
Sorry to report in hurry i mistakenly add in JetNews actually jt is in JetChat

**Comment by cryptrr** [comment]
Which is the compose version that you are using?

**Comment by cryptrr** [comment]
This is a bug with ToolTip. You can remove the tooltip and the events will work correctly.

**Comment by JolandaVerhoef** [comment]
Thanks for raising this! The issue was caused by our migration to `TooltipBox`, which handles long-presses internally. The fix is quite simple, we just tell the `TooltipBox` not to respond to long presses.

**Comment by shubham8360** [comment]
Thanks
