### ISSUE TITLE
Jetchat. Huge performance drop.

### ISSUE THREAD

**Issue by sergeyfitis** [android/compose-samples#131]
Huge performance tanking when selecting the text.

Steps to reproduce:
1. Enable `Profile HWUI rendering` to see performance bars.
2. Open the app
3. Select the text and start scrolling.

**Text not selected:**
<img src="https://user-images.githubusercontent.com/3204638/91622486-fc49fa80-e99f-11ea-8ed9-8cc6e62aa3f6.jpg" width="50%" height="50%"/>

**Text is selected:**
<img src="https://user-images.githubusercontent.com/3204638/91622516-14ba1500-e9a0-11ea-920d-e76355009070.jpg" width="50%" height="50%"/>

**Comment by JoseAlcerreca** [comment]
Thanks for the report although this is not an issue with the sample. I suggest you file a Compose bug in 
https://goo.gle/compose-feedback

(Feel free to link to this issue even if it's closed)

**Comment by sergeyfitis** [comment]
@JoseAlcerreca Thanks for the response. I've already created one https://issuetracker.google.com/issues/166769689
