### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by carlfindahl** [android/compose-samples#132]
What
----------------
Under Rally on the front page readme, it says:
    *"Custom layouts and reusable elementss"*

Fix
----------------
Should probably be "elements"

**Comment by giantthinker** [comment]
[music bamoun](https://musicbamoun.com)

**Comment by JoseAlcerreca** [comment]
Fixed in https://github.com/android/compose-samples/commit/6faccde2664252b1128008d740a40efadae181e4

thanks! Next time feel free to send a PR.
