### ISSUE TITLE
Pressing backspace doesn't delete last character in the "Email" field

### ISSUE THREAD

**Issue by shamilovstas** [android/compose-samples#135]
Steps to reproduce:
1. Build and launch the "Jetsurvey" sample app 
2. Start typing symbols in the "Email" field
3. Start deleting them using the "backspace" button on the keyboard
4. Once all characters expect the first one are deleted, verify that pressing the "backspace" button doesn't delete the last character. Instead, the cursor just shifts in front of that character without actually deleting it.

Recorded video: [jetpack-email-bug.tar.gz](https://github.com/android/compose-samples/files/5146794/jetpack-email-bug.tar.gz)

**Comment by Randyhubbard0** [comment]
What is the issue

**Comment by shamilovstas** [comment]
The issue is that upon deleting the last character (or, rephrasing, the character that was typed the first), doesn't get deleted. Instead, the cursor just "shifts" behind it, leaving it untouched. @Randyhubbard0 please, watch the video in attachments

**Comment by JoseAlcerreca** [comment]
This is a known issue. Fix will be available in alpha02
