### ISSUE TITLE
Using of dependencies.kt

### ISSUE THREAD

**Issue by tprochazka** [android/compose-samples#137]
I don't understand why you are using dependencies.kt in the examples.
It maybe makes sense in the large multi-module project (I think that use [Gradle Platform](https://docs.gradle.org/current/userguide/platforms.html#sub:using-platform-to-control-transitive-deps) would be better here).
but why in examples?

- it makes hard to copy&paste dependencies if you want to use the sample as source for your own project
- especially with a groovy build script, there is no way to crl+click to the definition location
- it prevents AS to automatically highlight outdated dependencies and automatically update them

**Comment by JoseAlcerreca** [comment]
It's way easier to manage dependencies with buildSrc.

However, we know not everyone is familiar with this so we left JetNews _copypasteable_:

https://github.com/android/compose-samples/blob/master/JetNews/app/build.gradle
