### ISSUE TITLE
Jetsnack does not remember scroll state position

### ISSUE THREAD

**Issue by jasonostrander** [android/compose-samples#139]
Looking at the code, it appears that JetSnack should remember the scroll state position in the horizontally scrolling rows. However, in my testing, this is not working.

**Comment by JoseAlcerreca** [comment]
I assume you mean on configuration change? or when navigating back?

**Comment by nickbutcher** [comment]
It does retain scroll position over configuration change but not across navigation events. I think that this is beyond the scope of the simple navigation system in place until a full AAC Navigation solution arrives, so will close as WAI.
