### ISSUE TITLE
Images in Jetsnack example are no longer available

### ISSUE THREAD

**Issue by bashor** [android/compose-samples#1408]
https://github.com/android/compose-samples/blob/b7adb98ebe36b17c23bfb7d27a9fa93d7416e47e/Jetsnack/app/src/main/java/com/example/jetsnack/model/Snack.kt#L35-L226

**Comment by bashor** [comment]
FTR it works now

**Comment by bashor** [comment]
Doesn't work again

**Comment by sdeleuze** [comment]
FYI I have a talk next week where I would like to demo it.

**Comment by riggaroo** [comment]
Hi folks! Unsplash unfortunately turned down the soruce.unsplash.com links, and since we'd like to not need to use an API key - we've now switched to static images. Addressed in this pull request - https://github.com/android/compose-samples/pull/1422

**Comment by bashor** [comment]
@riggaroo thanks for the update!

**Comment by bashor** [comment]
JFTR: I've updated the online demo (https://zal.im/wasm/jetsnack) with images from the PR.
@sdeleuze FYI
