### ISSUE TITLE
[Bug]: Can't open JetLagged in IntelliJ IDEA 2024.2 EAP (Ultimate Edition)

### ISSUE THREAD

**Issue by StokeMasterJack** [android/compose-samples#1411]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### Is this an issue related to one of the samples?

- [X] Yes, this is a specific issue related to this samples repo.

### Sample app

Other (bug not related to sample app)

### What happened?

I get this error:
The project is using an incompatible version (AGP 8.4.0) of the Android Gradle plugin. Latest supported version is AGP 8.3.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by IanGClifton** [comment]
It looks like it's being tracked at https://youtrack.jetbrains.com/issue/IDEA-352815/Android-Gradle-Plugin-8.4.0-isnt-supported, but I'm a bit surprised they're a couple of versions behind.
