### ISSUE TITLE
This version of the Android Support plugin for IntelliJ IDEA (or Android Studio) cannot open this project, please retry with version 4.2 or newer.

### ISSUE THREAD

**Issue by learningWu** [android/compose-samples#144]
This version of the Android Support plugin for IntelliJ IDEA (or Android Studio) cannot open this project, please retry with version 4.2 or newer.

**Comment by shibasis0801** [comment]
Did you use the canary build ?
That is the one suggested in the docs. 
[https://developer.android.com/studio/preview](url)

**Comment by nickbutcher** [comment]
As [stated](https://github.com/android/compose-samples#-requirements), Compose requires canary versions on Android Studio.

**Comment by fabiobeoni** [comment]
Hello,
I have the same issue using Android Studio Canary 16... Please see the attached screenshots.

![screen1](https://user-images.githubusercontent.com/16882089/101620205-8b8d9200-3a14-11eb-9faa-6a6a2d2b9f0a.png)
![screen-2](https://user-images.githubusercontent.com/16882089/101620208-8cbebf00-3a14-11eb-8c66-0b715feee1f4.png)

**Comment by Lipao12** [comment]
mine worked when I changed the build gradle to 4.1.3
