### ISSUE TITLE
[Bug]: The project is using an incompatible version (AGP 8.5.0) of the Android Gradle plugin. Latest supported version is AGP 8.5.0-beta02 

### ISSUE THREAD

**Issue by JefFO0** [android/compose-samples#1441]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### Is this an issue related to one of the samples?

- [x] Yes, this is a specific issue related to this samples repo.

### Sample app

Jetsnack

### What happened?

The project uses a version of AGP which does not exist

### Relevant logcat output

```shell
The project is using an incompatible version (AGP 8.5.0) of the Android Gradle plugin. Latest supported version is AGP 8.5.0-beta02
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by escaper01** [comment]
I had the same issue just
go to this file **libs.versions.toml** under **[versions]**
I made this change `androidGradlePlugin = "8.4.1"`
then you can start syncing your gradle and VOILA
