### ISSUE TITLE
[FR]: new version 

### ISSUE THREAD

**Issue by Rakib78242** [android/compose-samples#1446]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is this a feature request for one of the samples?

- [X] Yes, this is a specific request related to this samples repo.

### Sample app

Crane

### Describe the problem

Slow app let open

### Describe the solution

Give me New version place

### Additional context

![Screenshot_20240820-072911](https://github.com/user-attachments/assets/74d192d8-25eb-40e3-84e5-8cdc2c67c7b9)
Give me New version

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dturner** [comment]
Not sure what you mean by "Slow app let open". Is it only slow when you run in `debug` mode? If so, that's a known issue - please trying building and running the `release` build variant. If you're still experiencing problems please file a new issue with more detail.
