### ISSUE TITLE
[Bug]: Jetcaster does not show any podcasts and doesn't respond to keyboard input

### ISSUE THREAD

**Issue by dturner** [android/compose-samples#1461]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### Is this an issue related to one of the samples?

- [X] Yes, this is a specific issue related to this samples repo.

### Sample app

Jetcaster

### What happened?

When running Jetcaster on the emulator, the app does not show any podcasts (which presumably it is supposed to), and when attempting to enter text into the search field, no text appears. 

[Screen_recording_20240909_154310.webm](https://github.com/user-attachments/assets/0f915b96-b4fe-450c-a861-4e119486b33e)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jdkoren** [comment]
I think there are 2 issues here.

Re loading podcasts, I ran the app on a couple of devices, including some emulators. On one of the emulators it did take a good few seconds to load podcasts, but they eventually did load, so at this moment I don't have a repro case. @dturner do the podcasts eventually load, or is it blank indefinitely?

Re the search bar, it seems we just never update the text as you type, it's [always just `""`][1]. That much is a quick fix, but the app doesn't have any actual search or text-matching logic, so it won't impact what items are displayed. 

[1]: https://github.com/android/compose-samples/blob/bf6dead27c11e9a05f1e493ed5949498fa26c569/Jetcaster/mobile/src/main/java/com/example/jetcaster/ui/home/Home.kt#L389

**Comment by javadude** [comment]
I'm getting a NetworkOnMainThreadException when fetching the podcasts, which filters all feeds down to an empty list, so the selectedCategory won't get updated, and discoverItems() just returns without adding any UI.

(I added a breakpoint at PodcastFetcher:83)

**Comment by jdkoren** [comment]
> I think there are 2 issues here...

Both of these have been addressed, so closing this issue.
