### ISSUE TITLE
[FR]: Clean structure

### ISSUE THREAD

**Issue by lon9man** [android/compose-samples#1476]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is this a feature request for one of the samples?

- [X] Yes, this is a specific request related to this samples repo.

### Sample app

Jetcaster

### Describe the problem

Hello, tried to understand how clean structure resolved in Jetcaster-app.

in the internet i saw image https://raw.githubusercontent.com/AliAsadi/Android-Clean-Architecture/master/screenshot/architecture0.png (and a lot of other similar).
it explains that each layer can ask next starting from outer to inner like Presentation -> Data -> Domain.

BUT inner layer **_should not know_** about next outer layer.
in some examples i saw that separate `Domain`-module doesn't have access to `Data`-module and `Presentation`-module.

Jetcaster also has separate modules `Domain`, `Data`, `Mobile` (presentation). i expected that logic will work in 'clean structure'-way.
BUT in Jetcaster i see that it works in opposite way and **Domain-module has access to Data-module**:
```
// Jetcaster/core/domain/build.gradle.kts
implementation(projects.core.data)
```

am i missed something or it is truly violates 'clean structure'-concept?
thanks!

### Describe the solution

please help to understand the reason of described above.

maybe: Domain-module should not have access to Data-module to prevent violation 'clean structure'-concept?

thanks!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dturner** [comment]
Jetcaster follows the official Android architecture guidance where the domain layer is dependent on the data layer. This is different from clean architecture. 

More details here: https://developer.android.com/topic/architecture/domain-layer
Differences between Android official architecture and clean architecture: https://github.com/android/nowinandroid/discussions/1273#discussioncomment-8759098
