### ISSUE TITLE
[Bug]: Build warning hasRoute ReplyNavigationComponents.kt

### ISSUE THREAD

**Issue by tberghuis** [android/compose-samples#1483]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### Is this an issue related to one of the samples?

- [X] Yes, this is a specific issue related to this samples repo.

### Sample app

Reply

### What happened?

Build warning for `hasRoute` usage line 486 

    NavDestination.hasRoute can only be called from within the same library group (referenced groupId=`androidx.navigation` from groupId=`Reply`)

Whats the alternative to using hasRoute method?
I heard to use this method from @ianhanniballake https://medium.com/@ianhlake/theres-a-hasroute-extension-method-on-navdestination-specifically-for-exactly-this-b6f744c6f734

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by IanGClifton** [comment]
@dturner Do you know the guidance here?

**Comment by dturner** [comment]
@tberghuis When you say "build warning" what do you mean? What command are you using to perform the build? 

Or do you mean you're seeing a red line in Android Studio under the `hasRoute` method? If so, that's the lint checker in Android Studio, and yes, there's a known problem with it. 

It seems that in LadyBug, the lint checker is incorrectly reporting that `hasRoute` is accessible only from the navigation library, when in fact [it is a public method](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:navigation/navigation-common/src/main/java/androidx/navigation/NavDestination.kt;l=855?q=NavDestination.hasRoute&ss=androidx)

I've filed a bug for this here: https://issuetracker.google.com/372175033

Please upvote if this is affecting you, or provide more details if that's not the issue you're experiencing.

**Comment by tberghuis** [comment]
@dturner yeah I meant the lint checker. Thanks
