### ISSUE TITLE
FrameLayout.setContent vs ComposeView.setContent

### ISSUE THREAD

**Issue by mayojava** [android/compose-samples#149]
For the Fragment Views in Jetsurverysample app, what was the rationale for going for :

`FrameLayout` and calling `setContent` within it as oppose to inflating a layout with `ComposeView` and calling`setContent` on that instead, since `ComposeView` has been recommended as the way to go into compose world from the view system world.

**Comment by JoseAlcerreca** [comment]
I don't think ComposeView was available when the fragment was created. 

Thanks for catching it.
