### ISSUE TITLE
Cannot import project in Android Studio

### ISSUE THREAD

**Issue by Dambakk** [android/compose-samples#15]
Hi!

I am following the import instructions here: https://developer.android.com/jetpack/compose/setup#sample but get the following error in Android Studio (posted in the Kotlin-slack): https://kotlinlang.slack.com/archives/CJLTWPH7S/p1572702912308100

When pressing finish I get a dialog saying "Failed to find any projects in Git repository". Copying and opening the URL leads to the correct repo, and cloning and opening the repo in AS works fine. Others are also getting this error.

**Comment by gildor** [comment]
It's happening because there is no project in root for of repo, JetNews is subdirectory which project itself

**Comment by Dambakk** [comment]
I see. Changing the url to point to the subdirectory sounds like an easy thing to do. I guess someone responsible will fix it.

**Comment by dimsuz** [comment]
Maybe this should be reported on the android issue tracker instead of Github?
Otherwise, yes, feels like a one-line fix which really should be done, spoils the fun of swiftly following a nicely written onboarding tutorial.

**Comment by Dambakk** [comment]
Yeah, I agree, and the tutorials are really good!
I think this is it: https://issuetracker.google.com/issues/143634579

**Comment by nickbutcher** [comment]
Thanks for reporting, the docs have been updated to point to the sub-directory.

**Comment by dimsuz** [comment]
@nickbutcher Are you sure this is a docs only issue? The import still fails.

I.e. if I follow official Compose tutorial and do this:

```
File -> New -> Import sample -> Jetnews sample
```

It still fails with an error reported above.
It seems that some index file needs to be updated too somewhere

**Comment by nickbutcher** [comment]
Ah I see and can repro. Re-opening and investigating.

**Comment by nickbutcher** [comment]
Thanks again for reporting, this was an incompatibility between Android Studio's sample importer and the `kts` build script this project uses. This has been fixed internally and will be released in an upcoming version of Android Studio. I'll leave this bug open and resolve when it is released.

**Comment by nickbutcher** [comment]
Fixed in [AS 4.0 Canary 2](https://developer.android.com/studio/preview).
