### ISSUE TITLE
error in build.gradle

### ISSUE THREAD

**Issue by kondratenko930** [android/compose-samples#155]
import error  (AS Canary 10) in 
import com.example.jetsnack.buildsrc.Libs
import com.example.jetsnack.buildsrc.Versions

**Comment by kondratenko930** [comment]
decided! in dependencies.kt need to change

**Comment by kondratenko930** [comment]
need to change const val androidGradlePlugin = "com.android.tools.build:gradle:4.2.0-alpha08"  to const val androidGradlePlugin = "com.android.tools.build:gradle:4.2.0-alpha10"

**Comment by gastsail** [comment]
For me I replaced

```
 dependencies {
        classpath Libs.androidGradlePlugin
        classpath Libs.Kotlin.gradlePlugin
    }
```

With

```
 dependencies {
        classpath 'com.android.tools.build:gradle:4.2.0-alpha09'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.4.0"
    }
```

**Comment by kondratenko930** [comment]
> For me I replaced
> 
> ```
>  dependencies {
>         classpath Libs.androidGradlePlugin
>         classpath Libs.Kotlin.gradlePlugin
>     }
> ```
> 
> With
> 
> ```
>  dependencies {
>         classpath "com.android.tools.build:gradle:4.2.0-alpha09"
>         classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.4.0"
>     }
> ```

**Comment by hujincan** [comment]
> import error (AS Canary 10) in
> import com.example.jetsnack.buildsrc.Libs
> import com.example.jetsnack.buildsrc.Versions

This error also bothered me😫

**Comment by nickbutcher** [comment]
We updated all samples to `alpha03` and AGP `4.2.0-alpha10` in #179

**Comment by codeslubber** [comment]
If the samples were updated, how come I am still seeing this error, having just cloned them a few days ago?

**Comment by fanzhouyou** [comment]
> If the samples were updated, how come I am still seeing this error, having just cloned them a few days ago?

+1

**Comment by agu5a** [comment]
+1

**Comment by kidcats** [comment]
> +1
> Android Studio Arctic Fox | 2020.3.1 Canary 4
> Build #AI-202.7319.50.2031.7049475, built on December 24, 2020
> Runtime version: 11.0.8+10-b944.6842174 amd64
> VM: OpenJDK 64-Bit Server VM by N/A
> Windows 10 10.0
> GC: G1 Young Generation, G1 Old Generation
> Memory: 2048M
> Cores: 8
> Registry: external.system.auto.import.disabled=true
> Non-Bundled Plugins: org.jetbrains.kotlin, com.google.mad-scorecard

i have the same error ,could you solve this error ?

**Comment by kondratenko930** [comment]
Memory: 2048M -this is very little
