### ISSUE TITLE
Launch on Emulator

### ISSUE THREAD

**Issue by masterj3y** [android/compose-samples#159]
I've wrote a sample then whenever i try to launch it on AVD gradle builds project Successfully but nothing shows up on Emulator

compose = 1.0.0-alpha02
kotlin = 1.4.0
gradle plugin = 4.2.0-alpha10
gradle = 6.6.1

**Comment by nickbutcher** [comment]
This doesn't seem like an issue with this project. Please can you ask on [Slack](http://slack.kotlinlang.org/) or [StackOverflow](https://stackoverflow.com/questions/tagged/android-jetpack-compose)?
