### ISSUE TITLE
Poor performance

### ISSUE THREAD

**Issue by qianlvable** [android/compose-samples#16]
this demo is too laggy to attract new comer ：(
profile on pixel 3xl
![image](https://user-images.githubusercontent.com/5251057/68284303-32885780-00b8-11ea-94d6-3fa0f6177965.png)

**Comment by qianlvable** [comment]
![image](https://user-images.githubusercontent.com/5251057/68284458-8c891d00-00b8-11ea-9127-a31206650a5e.png)
cross fade is laggy

**Comment by nickbutcher** [comment]
Thank you for the report. Jetpack Compose is currently in Developer Preview and has not been heavily optimized for performance. Closing this issues.

**Comment by Jaimies** [comment]
@nickbutcher Is Jetpack Compose production-ready now, given that it's in alpha?
