### ISSUE TITLE
Jetsurvey: can't delete first char in OutlinedTextField

### ISSUE THREAD

**Issue by danaugrs** [android/compose-samples#160]
Can't delete the first character in all `OutlinedTextField`s.
Also, the text field is partially out of the screen when the "Invalid email" message is visible.
See both issues below:

![jetsurvey-bug1](https://user-images.githubusercontent.com/5261448/92610180-cce39980-f28d-11ea-877a-e12536ec5619.gif)

**Comment by waseefakhtar** [comment]
I think it's a known issue in 1.0.0-alpha01 and should be solved in 1.0.0-alpha02.

**Comment by nickbutcher** [comment]
https://issuetracker.google.com/issues/165956313 – Should be fixed in **alpha03** I believe.
