### ISSUE TITLE
Is overdraw problem solved in Jetpack Android Compose?

### ISSUE THREAD

**Issue by NurseyitTursunkulov** [android/compose-samples#18]
I found out that Compose uses the Linear Layout. Since Linear layout can cause overdraw problems and bad UX, had you take into consideration this?

**Comment by nickbutcher** [comment]
Not sure what you mean about using `LinearLayout`? Overdraw can still be an issue i.e. you can do more work than necessary. Closing this issue as unrelated to samples. Recommend you [join the chat](http://slack.kotlinlang.org/) to discuss this kind of question.
