### ISSUE TITLE
[Owl] Scroll issue

### ISSUE THREAD

**Issue by nglauber** [android/compose-samples#183]
I found this issue during details scrolling.

<img width=480 src="https://user-images.githubusercontent.com/6018094/93725264-0ec0e980-fb84-11ea-9ac3-34a2eedfb337.gif" />

**Comment by nickbutcher** [comment]
Thanks for reporting. I'm planning to migrate this screen to use the new [`BottomSheetScaffold`](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-master-dev:compose/material/material/src/commonMain/kotlin/androidx/compose/material/BottomSheetScaffold.kt;l=267) which should hopefully also address this.

**Comment by Jeyhey** [comment]
I have the impression that all Jetpack Compose Views have this problem of propagating clicks to the views below. In the JetSnack example this happens with the bottom bar and in my project also with `BottomDrawerLayout`.

**Comment by inktomi** [comment]
Having an official `BottomSheetScaffold` in the samples will be great!

**Comment by simona-anomis** [comment]
Not reproducible any more, so closing it.
