### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by juvebogdan** [android/compose-samples#206]
Hello,
 I am just starting with compose and when i try to build these projects (Jetsnack and Jetcaster) I get error like this:

Type com.example.jetsnack.model.SearchCategoryCollection-$$ExternalSynthetic0 is defined multiple times:

Execution failed for task ':app:mergeProjectDexDebug'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.DexMergingTaskDelegate
   > There was a failure while executing work items
      > A failure occurred while executing com.android.build.gradle.internal.tasks.DexMergingWorkAction

**Comment by nickbutcher** [comment]
Looks like you updated AGP to `4.2.0-alpha12` which exposes this r8 bug? If so then try the `dev_alpha04` branch which contains fixes or we'll merge these to `master` when Compose `alpha04` is released tomorrow.

**Comment by juvebogdan** [comment]
Thnak you.
Yes, I updated to 4.2.0-alpha12.

**Comment by nickbutcher** [comment]
Ok, I'll close as WAI as code should work fine unchanged (with AS 4.2c11)

**Comment by juvebogdan** [comment]
I went to dev_alpha04 and code builds fine but when deployed on real device running android 10 (Pixel 1) app crashes as soon as it is started
