### ISSUE TITLE
Very slow perfomance

### ISSUE THREAD

**Issue by NurseyitTursunkulov** [android/compose-samples#21]
I installed JetNews app, it works very very slowly. The worst UX, I have to wait for 7-10 seconds before it navigates to another screen. Please check it.

**Comment by nickbutcher** [comment]
Jetpack Compose is currently in Developer Preview and has not been optimised for performance. Closing this issue.

**Comment by iRYO400** [comment]
It's still same for today (11.14.2020)
Tested on Huawei P20 Lite

**Comment by anlexN** [comment]
just preview my background, it costs me 47s, oh my god. i am very very angry.

**Comment by NurseyitTursunkulov** [comment]
Android team as always weak, compared with iOS

**Comment by muhammadalkady** [comment]
It's still same for today

**Comment by jgavazzisp** [comment]
It seems to happen only on the very first screen loaded.

**Comment by mahdisml** [comment]
So true ! It happen only in first startup !

> 
> 
> It seems to happen only on the very first screen loaded.

@nickbutcher please open this thread :)

**Comment by daniel-micic** [comment]
same thing happening in stable release. why is this not opened again ?

**Comment by ezebongiovi** [comment]
> Jetpack Compose is currently in Developer Preview and has not been optimised for performance. Closing this issue.

If so, it should not have a stable version yet. this performance issue is completely ruining the user experience that Android can offer.An Android Developer should not deliver a feature performing like this, therefore, it should not be a stable version of the lib

Still having performance issues on `v1.0.2`

**Comment by hamthelegend** [comment]
My debug version is also slow, but the release build (with minify enabled) is super performant. Geez people. Why are you so angry. lol. Just say your problems in a civilized fashion.

**Comment by muhammadalkady** [comment]
@hamthelegend Jetpack compose still run in interpreted mode in release the first few times. So it is slow at first which is important for UX.

**Comment by hamthelegend** [comment]
AFAIK, the release build does not @muhammadalkady. Correct me if I'm wrong

**Comment by muhammadalkady** [comment]
@hamthelegend even in release mode still runs in interpreted mode.
https://developer.android.com/jetpack/compose/performance#use-baseline
You can see here that it is running in interpreted mode.
