### ISSUE TITLE
[JetNews]Text selection action drawing error on scroll

### ISSUE THREAD

**Issue by OumaSyuu** [android/compose-samples#229]
Text selection jumps over statusBar or bottomNavigationBar.
![Screenshot_20201015_141801_com example jetnews](https://user-images.githubusercontent.com/14196120/96084512-ca5e0a80-0ef1-11eb-85a7-b386179f9f3a.jpg)
![Screenshot_20201015_141819_com example jetnews](https://user-images.githubusercontent.com/14196120/96084521-ce8a2800-0ef1-11eb-9c05-008cf54b455f.jpg)

**Comment by JolandaVerhoef** [comment]
Can't reproduce.
