### ISSUE TITLE
[Crane] Unable to scroll the content

### ISSUE THREAD

**Issue by LouisCAD** [android/compose-samples#230]
Tested on a Pixel 2XL running Android 11 with Compose 1.0.0-alpha05 and no custom modifications.

**Comment by nickbutcher** [comment]
Can you clarify what content you're struggling to scroll? Thanks!

**Comment by LouisCAD** [comment]
The content on the white background ("Explore Flights by Destination"). I think it'll be obvious once you try it.

I think there's an issue with nested scrolling as the scrollable content is in a card that (in theory) can be dragged as well.

**Comment by manuelvicnt** [comment]
Ah! Yes, thanks for reporting this. This is indeed a bug with nested scrolling. The content inside the backdrop is able to scroll until certain position but not entirely. There's nothing we can do about this until we have better APIs, closing this for now. Thanks!

**Comment by LouisCAD** [comment]
I opened this issue so I could keep track of the APIs being improved for this + it being actually fixed in the sample so I could see it work.

I'm not sure closing it will help, I fear it'll just be forgotten and I'll not be able to test before it's quite late to give further feedback.

@manuelvicnt You say "closing this for now". Did you really have a plan to reopen this once the APIs are improved, and a way to ensure this is not forgotten?
