### ISSUE TITLE
[JetChat] TextField stops reacting once it loses focus once

### ISSUE THREAD

**Issue by Anvell** [android/compose-samples#234]
This behaviour was introduced with alpha-05 update.

Steps to reproduce:
1. Tap on text field.
2. Enter some text.
3. Tap away, so it loses focus.
4. There is no way of entering text edit mode.

**Comment by JoseAlcerreca** [comment]
Let's track all focus issues here

I'll add this report from slack:

- launch the app
- click anywhere outside the message input field
- try clicking on the input field to type the message
- keyboard does not show up

**Comment by JoseAlcerreca** [comment]
I found a bug in Jetchat, but that didn't fix it (`keyboardController  is always null in `UserInputText`)

Looks like https://android-review.googlesource.com/c/platform/frameworks/support/+/1456460 is fixing this general problem which will probably remove a lot of boilerplate in UserInput. Let's wait until that lands.

**Comment by JoseAlcerreca** [comment]
Problem still exists in alpha09.

**Comment by JoseAlcerreca** [comment]
Tracked in https://issuetracker.google.com/164859446

**Comment by Lawhacknifemi** [comment]
Has this been fixed ? 
It facing a similar issue on a project I'm working on

**Comment by astamato** [comment]
Does it still happen in latest rc?
