### ISSUE TITLE
[JetChat] Text selection does not work in text fields

### ISSUE THREAD

**Issue by Anvell** [android/compose-samples#235]
Compose alpha05 introduced some changes which disabled text selection in all of TextFields, perhaps it's not a bug but a feature and needs to be addressed in a proper way, but there is no mention of this in compose change logs.

**Comment by JoseAlcerreca** [comment]
Seems to work in alpha08.
![image](https://user-images.githubusercontent.com/609125/100231591-85cd8200-2f27-11eb-963a-2eb9c3a09939.png)
