### ISSUE TITLE
[Jetsnack] Layer is redrawn for LayoutNode in state NeedsRelayout

### ISSUE THREAD

**Issue by ghost** [android/compose-samples#236]
I got this error while using jetsnack project. I was switching between bottom navigation tabs.

java.lang.IllegalArgumentException: Layer is redrawn for LayoutNode in state NeedsRelayout [LayoutNode@b55d13b children: 0 measureBlocks: androidx.compose.ui.LayoutKt$measureBlocksOf$1@7ec4058]

**Comment by bentrengrove** [comment]
I haven't been able to reproduce this so I assume it has been fixed by Compose updates. Please reopen if this is still an issue.
