### ISSUE TITLE
about Lazy ScrollChilden questions

### ISSUE THREAD

**Issue by hongcanyang** [android/compose-samples#245]
LazyForRow and other widget only support for know the childen item layout at the visible. but
1、 how to know the item at invisible.
2、and can support to layout the item at the visible left and right item at advance like viewpager
3、can support the cache function for it.

**Comment by nickbutcher** [comment]
These are not issues with the samples in this repo. Please can you ask on [StackOverflow](https://stackoverflow.com/questions/tagged/android-jetpack-compose) or [Slack](http://slack.kotlinlang.org/)? Thanks!
