### ISSUE TITLE
ViewModels

### ISSUE THREAD

**Issue by enciyo** [android/compose-samples#255]
# Untitled

```kotlin
@OptIn(ExperimentalLazyDsl::class)
@Composable
fun PodcastCategory(
    categoryId: Long,
    modifier: Modifier = Modifier
) {
    /**
     * CategoryEpisodeListViewModel requires the category as part of it's constructor, therefore
     * we need to assist with it's instantiation with a custom factory and custom key.
     */
    val viewModel: PodcastCategoryViewModel = viewModel(
        // We use a custom key, using the category parameter
        key = "category_list_$categoryId",
        factory = viewModelProviderFactoryOf { PodcastCategoryViewModel(categoryId) }
    )

    val viewState by viewModel.state.collectAsState()
```

I think this use is dangerous. ViewModels were created for each category and added ViewModelStore. As far as I know , this ViewModelStore is a Static Ambient. And that will never removed (If Didn't start activity etc.). So how correct is this approach?

**Comment by chrisbanes** [comment]
Agreed, this isn't optimal, but it's not dangerous imo. The `viewModel()` function currently scopes all of it's `ViewModel`s to the host fragment if available, else Activity. This does mean that the `ViewModel`s are currently only cleared once the Activity has been destroyed.

Once we have a better way to scope ViewModels we will use it in Jetcaster, but at the moment this as good as we can get.

See #237 which adds similar support to Crane.

**Comment by enciyo** [comment]
Thank you for information.
