### ISSUE TITLE
`SwipeToRefreshLayout` with a `LazyColumnForIndexed` issue

### ISSUE THREAD

**Issue by s4cha** [android/compose-samples#267]
Hi I'm writing here because I don't know where else I could get help on that, I think this is more of a Compose issue.

I am having trouble making `SwipeToRefreshLayout` work with `LazyColumnForIndexed`, in order to have both "pull to refresh" functionality and  infinite scroll "Load more" paging.

This issue is easily reproducible in **JetNews**.
If you replace `ScrollableColumn` by `LazyColumnForIndexed` in the JetNews project, `SwipeToRefreshLayout` stops working.

I'm probably missing something obvious though. I believe `SwipeToRefreshLayout` & `LazyColumnForIndexed` combination is one of the biggest building block of any "feed-based" app, so this use case looks pretty important to support.

Any Ideas to make `SwipeToRefreshLayout` work with a `LazyColumnForIndexed` ?

Thanks a ton in advance.

**Comment by nickbutcher** [comment]
Thanks for reporting. This is a [known issue that has just been fixed](https://issuetracker.google.com/issues/171389491), should be available in `alpha07`.
