### ISSUE TITLE
[Jetchat]The project is using an incompatible version (4.2.0-alpha15) of the Android Gradle plugin.

### ISSUE THREAD

**Issue by mdddj** [android/compose-samples#274]
```
The project is using an incompatible version (4.2.0-alpha15) of the Android Gradle plugin.
Upgrade to the latest version
```
Click on the  `Upgrade to the latest version` Pop up the following prompt
```
This project is using version 4.2.0-alpha15 of the Android Gradle plugin, which is incompatible with this version of Android Studio.
To continue importing this project (Jetchat), Android Studio will upgrade the project's build files to use version 4.2.0-alpha16 of Android Gradle plugin (you can learn more about this version of the plugin from the release notes).
```
and
```
The Upgrade Assistant failed to upgrade this project, finding no way of performing the Upgrade AGP version from 4.2.0-alpha15 to 4.2.0-alpha16 command, possibly because the project's build files use features not currently supported by the Upgrade Assistant (for example: using constants defined in buildSrc, or other unrecognized constructs, in Gradle build files).
```

**Comment by JustJerem** [comment]
Hi @mdddj,
In the file `dependencies.kt`, change the Android Gradle Plugin for the version `4.2.0-alpha16`.

You can find `dependencies.kt` at the path :
> src/main/java/com/example/compose/jetchat/buildsrc/dependencies.kt

The Android Gradle Plugin must look like this at the end :
>     const val androidGradlePlugin = "com.android.tools.build:gradle:4.2.0-alpha16"

After that, `Sync your project with Gradle files`. 🎉

**Comment by nickbutcher** [comment]
Thanks, we upgrade to latest AGP with each Compose alpha update (every 2 weeks); this is already happening on the latest `dev_` branch. Closing issue.

**Comment by wafiazmihartono** [comment]
@JustJerem Could you explain to me why this sample declares its dependencies in that file instead of the regular build.gradle? And is there any documentation on this matter?
