### ISSUE TITLE
Adding a new theme - Reply 

### ISSUE THREAD

**Issue by samsruti** [android/compose-samples#275]
I would like to add a new material theme "Reply" - Developed using JetPack Compose.

**Comment by samsruti** [comment]
https://github.com/android/compose-samples/pull/276

**Comment by nickbutcher** [comment]
Thank you very much for the contribution! Unfortunately we will not be able to merge this into the repo as we are not looking to expand the number of samples at this time.

The team is dedicated to maintaining the samples in this repo (we update them every 2 weeks for each new Compose alpha release) and are not looking to expand this work right now. Also, per the [contribution guide](https://github.com/android/compose-samples/blob/dev_alpha07/CONTRIBUTING.md#contributing-a-patch), it would have been nice to discuss on an issue *before* submitting this PR.

We're glad that you're excited about Compose and we would love contributions to the existing apps should you like to get involved in the future but adding a whole new sample isn't feasible right now.

**Comment by samsruti** [comment]
Thanks, @nickbutcher . 
I will definitely look forward to improve the existing samples :D

**Comment by samsruti-dash** [comment]
Hi @nickbutcher 

Is the team open to accepting new themes?
I was thinking to revamp the codebase again?

**Comment by samsruti** [comment]
Hi @nickbutcher ,

I was wondering if your team is ready to accept new themes?

I was hoping to revamp it again as it is very old code 😛
