### ISSUE TITLE
Low-performance in debug mode

### ISSUE THREAD

**Issue by Tougee** [android/compose-samples#28]
Nice demo for compose!

I've install this demo in debug mode, seems loses much frames, especially when open new page. So I open GPU render analysis in Developer mode, and the result not good like the below picture

<img src="https://user-images.githubusercontent.com/9980196/69304811-f7ac2500-0c5c-11ea-87b8-0a9f7a6491b9.jpeg" width="30%" height="30%"/>

**Comment by nickbutcher** [comment]
Thanks for taking a look! Jetpack Compose is currently in Developer Preview and we are not currently focused on performance optimization. Closing this as WAI for now.
