### ISSUE TITLE
[ jetsnack ] How to customize the indicator color, width and height of TabRow or ScrollableTabRow 

### ISSUE THREAD

**Issue by MannaYang** [android/compose-samples#286]
[Here is the official syntax document, but only part of the code fragment, I don't know how to customize this function](https://developer.android.com/reference/kotlin/androidx/compose/material/package-summary#tabrow)

**Comment by JoseAlcerreca** [comment]
Please use Stackoverflow for general questions

**Comment by shoanchikato** [comment]
I hope this will help the next person that lands on this pages:

`TabRow(
                    selectedTabIndex = state,
                    backgroundColor = MaterialTheme.colors.background,
                    contentColor = contentColorFor(MaterialTheme.colors.background),
                    indicator = @Composable { tabPositions ->
                        TabRowDefaults.Indicator(
                            height = 4.dp,
                            color = MaterialTheme.colors.primary,
                            modifier = Modifier.tabIndicatorOffset(tabPositions[state])
                        )
                    },
                    divider = {},
                ) {}`

**Comment by CoolMind** [comment]
See https://stackoverflow.com/questions/73448151/how-do-i-remove-undeline-of-tabrow-in-jetpack-compose, https://stackoverflow.com/questions/76695156/using-primary-tabs-using-jetpack-compose.
