### ISSUE TITLE
[Proposal] Just a question, can one of the samples use DataStore?

### ISSUE THREAD

**Issue by XinyueZ** [android/compose-samples#296]
Maybe I have missed one, but if not, can it be a proposal?

**Comment by florina-muntenescu** [comment]
Thank you for your proposal. There is no connection between Compose and DataStore. If you're looking to save a UI preference on disk, this should happen away from the UI layer and the UI layer should not know (or care) where and how that preference is saved. Usually, the ViewModel will be the class responsible for saving / retrieving such a preference from a repository / data source. 

You can see how this is done using Views and DataStore [here](https://github.com/googlecodelabs/android-datastore).
