### ISSUE TITLE
[Owl] Question: Converting to Compose Navigation 

### ISSUE THREAD

**Issue by qrezet** [android/compose-samples#311]
https://github.com/android/compose-samples/blob/2cff65334ea023956a58f215a13b6a55c7e1e18f/Owl/app/src/main/java/com/example/owl/ui/courses/Courses.kt#L77-L82

Just wondering why the following wasn't converted to Navigation Compose?

**Comment by Jeyhey** [comment]
Apparently, this repository is a very bad place to give feedback and ask questions. There is almost no reaction. I wonder why, on other communication channels there seem to be more efforts to get users involved.

**Comment by qrezet** [comment]
@Jeyhey, lets wait patiently. I believe there is a valid reason for this. 

1) People who worked on this samples have way more important things to do than just maintaining this samples. This is just one of the things they do and probably not even very important compared to other task.
2) Compose is still very much changing. It is possible that answers to question like this are still up in the air.

**Comment by JoseAlcerreca** [comment]
Hey @qrezet good question, we're still discussing how to correctly implement this
 - Two nested NavHosts
 - Using a nested graph with `navigation` which requires some hoisting
I'm experimenting with it in https://github.com/JoseAlcerreca/compose-samples/pull/1

> very bad place to give feedback and ask questions. 

Not true if, like this issue, it is about samples and not the toolkit.

**Comment by qrezet** [comment]
Hi @JoseAlcerreca, is there anything you could share or discover where experimenting on this? I am currently in the same situation and was also wondering what should I do. Specifically whether I should nest `NavHost` or make it a flat (Single) `NavHost`.
