### ISSUE TITLE
[Dev docs] Change androidx.ui:ui-tooling to androidx.compose.ui:ui-tooling

### ISSUE THREAD

**Issue by vikrama** [android/compose-samples#313]
https://developer.android.com/jetpack/compose/setup mentions the following dependency:
androidx.ui:ui-tooling:1.0.0-alpha08

Can you change it to androidx.compose.ui:ui-tooling:1.0.0-alpha08 please?

Related: https://stackoverflow.com/questions/64961333/gradle-cant-resolve-androidx-uiui-tooling-dependency-by-google-repository

**Comment by nickbutcher** [comment]
Thanks for letting us know, I'll get this fixed. FYI you can use goo.gle/compose-feedback to file issues with the Compose project/documentation—this issue tracker is for the samples.
