### ISSUE TITLE
[jetchat] TouchEvents are ignored on api <=25

### ISSUE THREAD

**Issue by j-ns** [android/compose-samples#318]
Scrolling the conversation messages is not working until a toolbar icon is clicked, which causes the previous events to be handled. The same effect occurs on the UserInput composable.

**Comment by JoseAlcerreca** [comment]
I tried repro on a API 21 emulator and it works fine. Also there are tests covering this in API 23. Can you add more details?

**Comment by j-ns** [comment]
I see the issue on:
device huawei p9 lite api 23
emu nexus 5 api 23
emu pixel2 xl api 25

On the nexus emu the profile screen is empty, showing only a white background while on the other device / emu the profile screen can only be scrolled once, before it freezes and stops reacting to touch events.

**Comment by j-ns** [comment]
I see the issue on:
device huawei p9 lite api 23
emu nexus 5 api 23
emu pixel2 xl api 25

On the nexus emu the profile screen is empty, showing only a white background while on the other device / emu the profile screen can only be scrolled once, before it freezes and stops reacting to touch events.

I see the issue on:
device huawei p9 lite api 23
emu nexus 5 api 23
emu pixel2 xl api 25

On the nexus emu the profile screen is empty, showing only a white background while on the other device / emu the profile screen can only be scrolled once, before it freezes and stops reacting to touch events.




I see the issue on:
device huawei p9 lite api 23
emu nexus 5 api 23
emu pixel2 xl api 25

On the nexus emu the profile screen is empty, showing only a white background while on the other device / emu the profile screen can only be scrolled once, before it freezes and stops reacting to touch events.

**Comment by j-ns** [comment]
The issues occured after the commits on Dec 3, 2020
