### ISSUE TITLE
[jetchat] Opening application with keyboard opened

### ISSUE THREAD

**Issue by Vivecstel** [android/compose-samples#320]
When opening the application with keyboard opens something is off. 

![jetsnack keyboard open](https://user-images.githubusercontent.com/3096681/102077489-0fc78700-3e12-11eb-87b4-7ffb461581a4.png)

**Comment by JoseAlcerreca** [comment]
I can't reproduce, which API level/device is this?

**Comment by Vivecstel** [comment]
I used Xiaomi mi a3. Searched the application via search bar and opened it with keyboard opened. If needed, I can provide a small video.

**Comment by JoseAlcerreca** [comment]
No thanks, I played a bit more with it and found weirdness as well. Turns out there's no recomposition when the keyboard is hidden. Tracked in https://issuetracker.google.com/175864912

Thanks!

**Comment by JoseAlcerreca** [comment]
Looks fixed to me in toolkit. Please reopen if you find it again.
