### ISSUE TITLE
[jetchat] Orientation issue

### ISSUE THREAD

**Issue by Vivecstel** [android/compose-samples#321]
When doing an orientation in every screen, a blank screen is displayed.

![jetsnack orientation](https://user-images.githubusercontent.com/3096681/102077737-72b91e00-3e12-11eb-9330-0fa1a1b69c5f.png)

**Comment by JoseAlcerreca** [comment]
Confirmed in alpha09 too

**Comment by JoseAlcerreca** [comment]
Going back from androidx.fragment.app.FragmentContainerView to fragment solves the issue temporarily but we're investigating :eyes:

**Comment by JoseAlcerreca** [comment]
In snapshot 7123292 using `fragment` crashes the app as fragments need to be inflated exactly once. Looks like AndroidViewBinding is inflating more than once. Still looking into it.

**Comment by JoseAlcerreca** [comment]
Fixed in https://github.com/android/compose-samples/pull/399
