### ISSUE TITLE
Crane: changing android.enableJetifier=true

### ISSUE THREAD

**Issue by joreilly** [android/compose-samples#336]
Crane project currently uses `android.enableJetifier=true` due I believe to use of google maps dependencies.  Is there any plans to make changes to this can be set to false (assuming this is possible right now?)?

**Comment by joreilly** [comment]
possibly related to https://github.com/googlemaps/android-maps-ktx/issues/93

**Comment by manuelvicnt** [comment]
Not needed anymore, thanks! Will get shipped in the next libraries update

**Comment by manuelvicnt** [comment]
I'll keep an eye on this but yeah, it's still needed for `com.google.android.libraries.maps:maps`

**Comment by riggaroo** [comment]
@arriolac Hey Chris 👋🏻  Do you know if we can remove the `android.enableJetifier` with the new Maps Compose interop in Crane?

**Comment by arriolac** [comment]
Looks like before Maps Compose was integrated Crane depended on the V3 BETA version of the Maps SDK which requires `android.enableJetifier=true`. Maps Compose on the other hand, depends on the play services version of Maps which shouldn't require that flag. 

I've removed `android.enableJetifier=true` in PR #772. Assuming no other dependency requires it, we can close this issue.
