### ISSUE TITLE
This version of the Android Support plugin for IntelliJ IDEA (or Android Studio) cannot open this project, please retry with version 4.3 or newer.

### ISSUE THREAD

**Issue by dengshiwei** [android/compose-samples#338]
This version of the Android Support plugin for IntelliJ IDEA (or Android Studio) cannot open this project, please retry with version 4.3 or newer.
I use the canary build 4.2，and Can not find 4.3 on the downlod page https://developer.android.com/studio/preview.

**Comment by HankZhang** [comment]
same

**Comment by dengshiwei** [comment]
@HankZhang 下载 Canary 版本的就可以了，Beta 版本的不行.

**Comment by jboxx** [comment]
what the solution @dengshiwei?

**Comment by dengshiwei** [comment]
Just download the Canary version..
![image](https://user-images.githubusercontent.com/12447711/105667242-dd7f6e00-5f15-11eb-915a-97eebe5b23b9.png)

**Comment by forntoh** [comment]
@dengshiwei I have tried the latest canary version, and a newly created compose project does not build
See #424
