### ISSUE TITLE
Ultra Slow Preview Times

### ISSUE THREAD

**Issue by southerndevz** [android/compose-samples#354]
Wow, the rendering of the `@Preview` is very slow. I could’ve done the view equivalent faster in XML. This preview feature has to be fast if we are to use this in a real release. 

Also we would love to have a library (similar to a Palette) from which we can choose “composable” from because I’m really don’t know how many stock composable are there except for `Text(), Image(), FloatingActionButton()`and `Button()`

Other than that this is an interesting framework no more hunting for useless libraries for a circular image. 😁

**Comment by southerndevz** [comment]
Wow, the rendering of the `@Preview` is very slow. I could’ve done the view equivalent faster in XML. This preview feature has to be fast if we are to use this in a real release. 

Also we would love to have a library (similar to a Palette from which we can choose “composable” from because I’m really don’t know how many stock composable are there except for `Text(), Image(), FloatingActionButton()`and `Button()`

**Comment by nickbutcher** [comment]
Thanks for the feedback, but this is unrelated to this repo of samples. Perhaps you could file it on the [Android Studio Issue Tracker](https://developer.android.com/studio/report-bugs)?
