### ISSUE TITLE
TextField is not respond to  delete  when keyboard is number or Chinese 

### ISSUE THREAD

**Issue by miaoyanrssq** [android/compose-samples#364]

**Comment by JoseAlcerreca** [comment]
Please provide more information

**Comment by miaoyanrssq** [comment]
when I input  Chinese word ,  key delete is not work, I can't delete the word in TextField, but it's ok in English

**Comment by miaoyanrssq** [comment]
> Please provide more information

when I input Chinese word , key delete is not work, I can't delete the word in TextField, but it's ok in English

**Comment by JoseAlcerreca** [comment]
In which sample?

**Comment by Mbt925** [comment]
I could reproduce the numeric keyboard case. With a numeric keyboard, keeping down the delete button only deletes one character and then gets canceled (with this log: "IInputConnectionWrapper: sendKeyEvent on inactive InputConnection"):

```
var textState by remember { mutableStateOf("") }
TextField(
    value = textState,
    onValueChange = {textState70 = it},
    keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Number),
)
```
