### ISSUE TITLE
does not implement prepareCall

### ISSUE THREAD

**Issue by RalphBergmannKMB** [android/compose-samples#380]
I used the samples to create my own little app and run into this issue: 

<img width="853" alt="CleanShot 2021-02-09 at 01 20 00@2x" src="https://user-images.githubusercontent.com/47594120/107298071-fd19a900-6a74-11eb-91b1-7e651e9f6f03.png">

I was wondering why it works in the samples but not in my own project. I found the mistake, but I'm still wondering about it.
When I add `androidTestImplementation Libs.AndroidX.Compose.uiTest` it is gone. 

Why does adding an `androidTestImplementation` fixes the issue? Is this a bug in the samples or somewhere in Android or one of the used libraries?

**Comment by JoseAlcerreca** [comment]
Not related to samples

**Comment by RalphBergmannKMB** [comment]
This also happens in the examples when you remove the `androidTestImplementation Libs.AndroidX.Compose.uiTest`.
