### ISSUE TITLE
Jetpack  TexField not working  with  onImeActionPerformed()

### ISSUE THREAD

**Issue by ilyosbekibrohimov** [android/compose-samples#404]
Hi I am  trying to  make a custom search bar using  TexField, but  when  I used the onImeActionPerformed() function inside  of TextField, I got  an  error
![Capture](https://user-images.githubusercontent.com/46449085/108620818-01c95e80-7472-11eb-8e01-9c9e7787bced.PNG)
What may be the possible reason for that error?
Thanks

**Comment by ilyosbekibrohimov** [comment]
![Capture](https://user-images.githubusercontent.com/46449085/108620864-42c17300-7472-11eb-8cbb-b147c1d24acf.PNG)
This is the error I got when  I ran the code.

**Comment by Mastermind101-maker** [comment]
https://github.com/android/compose-samples/issues/404

**Comment by florina-muntenescu** [comment]
`onImeActionPerformed` was removed from `TextField`. The error gives you instructions on what to use.
