### ISSUE TITLE
[Feature request] Demo for Swipe to Refresh

### ISSUE THREAD

**Issue by PatilShreyas** [android/compose-samples#405]
Demo implementation for swipe to refresh/pull to refresh would be great if implemented in any one of the project.

**Comment by Jeyhey** [comment]
There is an example here: https://github.com/android/compose-samples/blob/main/JetNews/app/src/main/java/com/example/jetnews/ui/SwipeToRefresh.kt

But I find it less flawless than the current non-jetpack-compose implementation.

**Comment by PatilShreyas** [comment]
Thanks for the ref @Jeyhey. Closing issue since I got the reference.
