### ISSUE TITLE
No TextField samples

### ISSUE THREAD

**Issue by DolphinWing** [android/compose-samples#41]
Can you please provide TextField samples here? There are no much references about how to control TextField and focus. Please add sample.

**Comment by nickbutcher** [comment]
Thanks for the suggestion. There are some samples [here](https://android.googlesource.com/platform/frameworks/support/+/refs/heads/androidx-master-dev/ui/ui-framework/integration-tests/samples/src/main/java/androidx/ui/framework/samples/TextFieldSample.kt) but agree we could use more.

**Comment by wajahatkarim3** [comment]
I would love to do this. Can I create some samples?

**Comment by vbudilov** [comment]
I went through the same search and couldn't find anything so I created my own. It's not polished but it works. Will update it later but feel free to submit PRs. 
https://github.com/vbudilov/jetpack-compose-starter/blob/3a2b9c7c048502b3b02fd5246457c7b51b2860c8/app/src/main/java/com/budilov/starter/common/Inputs.kt#L24

**Comment by DolphinWing** [comment]
Look 1.0.0-alha01 released with Jetsurvey sample. It has multiple TextField samples.
