### ISSUE TITLE
[JetChat] ConversationTest fails on large screen device

### ISSUE THREAD

**Issue by pfmaggi** [android/compose-samples#410]
`ConversationTest` assumes that not all the messages fit on screen and it looks for the `R.string.jumpBottom` node to be visible after having scrolled to the top of the messages.  
This is not the case when running the test on a large screen device like a 10" tablet, all the messages fit on screen and the test fails:
![image](https://user-images.githubusercontent.com/188886/109285705-b15f5180-7821-11eb-8ca0-bbf14b8aeb21.png)

Screenshot from a Samsung Tab S7
![device-2021-02-26-105350](https://user-images.githubusercontent.com/188886/109285611-9391ec80-7821-11eb-916b-1df6b3eb8a99.png)

**Comment by JoseAlcerreca** [comment]
Done but I don't think we're going to add a tablet to CI for now, so here's proof :)

![image](https://user-images.githubusercontent.com/609125/109294653-c215c480-782d-11eb-9c1a-b11cbab73e9d.png)

![image](https://user-images.githubusercontent.com/609125/109294772-ea9dbe80-782d-11eb-9820-69d9786718b8.png)

**Comment by pfmaggi** [comment]
Thanks, LGTM
