### ISSUE TITLE
Compose tutorial - "Illegal version for 'Msi': '1.0' is not a valid version

### ISSUE THREAD

**Issue by bhprod** [android/compose-samples#414]
I am unable to run the project because of this error. Commenting out the "nativeDistributions" section allows me to run the project correctly however. 
<img width="1195" alt="Screen Shot 2021-02-26 at 11 31 45 AM" src="https://user-images.githubusercontent.com/55409635/109340591-727fca80-7826-11eb-8b20-e6db286d82db.png">

**Comment by JoseAlcerreca** [comment]
This is unrelated to samples, please post on SO.

**Comment by DetachHead** [comment]
change version to `"1.0.0"` instead of `"1.0"`
