### ISSUE TITLE
Now there is a beta version, but these demos are still hot, very slow and low performance. Please tell me if jetpack compose can really be used

### ISSUE THREAD

**Issue by albertPu** [android/compose-samples#415]
Now there is a beta version, but these demos are still hot, very slow and low performance. Please tell me if jetpack compose can really be used

**Comment by Luis0648** [comment]
Si adobe acróbata es la correcta*#*##*#*

**Comment by chaoslorenz** [comment]
I would stay well away from it, to be honest.

Google do not have a good track record for releasing things, without major issues with implementation.

Flutter is a train wreck.

Wait one year after it has been fully been released (it is only in beta at the moment) before touching.

At least waiting one year before using in a real production app, will reduce the risk.

Remember Google developers, do not care about you or your job, or business. They get paid regardless if this flops or not.

**Comment by albertPu** [comment]
Is the Android team weaker than the ios team？

**Comment by JoseAlcerreca** [comment]
Not an issue related to samples, please move to SO.
