### ISSUE TITLE
AppDrawer content is hardly clickable

### ISSUE THREAD

**Issue by amar1995** [android/compose-samples#42]
The content(Home, Intererts) in navigation drawer is hardly clickable and also background color is only covering the small area. In pervious version background color is taking the full width of navigation bar. <br>
![navigationContent](https://user-images.githubusercontent.com/16504922/71802205-1dfa1880-3083-11ea-8774-41e74372b167.png)

**Comment by rock3r** [comment]
This has been fixed in #45 // CC @nickbutcher

**Comment by nickbutcher** [comment]
Fixed in#45
