### ISSUE TITLE
The project can't be built correctly with Android Studio 4.2 beta 5

### ISSUE THREAD

**Issue by acaixuediananao** [android/compose-samples#421]
This version of the Android Support plugin for IntelliJ IDEA (or Android Studio) cannot open this project, please retry with version 4.3 or newer.

**Comment by geek5nan** [comment]
Canary Version of Android Studio is required, see [README](https://github.com/android/compose-samples/blob/main/README.md).

💻 Requirements
------------
To try out these sample apps, you need to use the latest [Canary version of Android Studio](https://developer.android.com/studio/preview)...

**Comment by nickbutcher** [comment]
As @geek5nan points out, [Canary version of Android Studio](https://developer.android.com/studio/preview) is required. Closing as WAI.

**Comment by forntoh** [comment]
@nickbutcher and @geek5nan, I have tried the latest canary version, and a **newly created** conpose project does not build
See #424
