### ISSUE TITLE
Question: Approach on SharedUI

### ISSUE THREAD

**Issue by qrezet** [android/compose-samples#423]
This is more of a question than an issue. 

Hi, was wondering what's your opinion about shared ui and how to do it in compose.

I created this sample app to demonstrate some questions I have.
[https://github.com/qrezet/SharedUiSample/blob/master/app/src/main/java/com/sample/sampleapp/MainActivity.kt](https://github.com/qrezet/SharedUiSample/blob/master/app/src/main/java/com/sample/sampleapp/MainActivity.kt) (The comments in the code highlights my questions)

I was wondering if it would be better to continue with this approach..

or

redefine the "shared ui" across each screen? similar to how [JetNews](https://github.com/android/compose-samples/tree/main/JetNews) is doing it.

I feel like redefining the "shared ui" across screens would solve most of my issues with the first approach but I also don't want my "shared ui" to be going in and out every time the user navigates from screen to screen.

Any recommendation? Thanks in advance.

**Comment by JoseAlcerreca** [comment]
Hi, these questions are better suited for Stackoverflow or Reddit so I'm going to close the issue.

However, it's a very good question which boils down to "how to pass an event _down_"  (or sideways in this case) and I don't think there's a simple answer. I cloned your repo and spent some time on it, asking the team as well. 

One option you have is to replace that `actionCallback` with something like `val saveEvents = remember { MutableSharedFlow<Unit>() }` and pass it down to both the TopAppBar and ScreenC. The button would call `saveEvents.emit(Unit)` and the screen could collect it as:
```
    val profileViewModel = viewModel<ProfileViewModel>()
    LaunchedEffect(saveEvents) {
        saveEvents.collect { profileViewModel.save(name, address) }
    }
 ```

We'll consider adding some guidance around this it to the documentation. Thanks!

**Comment by qrezet** [comment]
I'm sorry about posting here. I actually posted a similar question in Stackoverflow but didn't get any response. I also posted the same thing in the slack channel but also didn't get much feedback. I was desperate and though this was my last resort. So I really do apologize.

I have some more questions kind of related to this topic. I would love to share them if you're interested.

**Comment by JoseAlcerreca** [comment]
Yeah that would be the easy way to fix it in this particular case, but we can't hide from the problem forever :) 

What if you wanted to animate something in the AppBar() when a transition happens?

**Comment by qrezet** [comment]
Yes 100% agree. But there's alot of problem with the first approach though. 

If only 1 AppBar is maintained within the whole application, that single Shared AppBar would tend to bloat as it tries to handle all application's appbar configuration. Sharing the AppBar also takes away how flexible the Appbar could be. 

It would be really nice if docs could give guidance on how to handle such scenarios.

**Comment by qrezet** [comment]
Hi @JoseAlcerreca,

I'm sorry if this is a bother. Is there any news on this?
