### ISSUE TITLE
[JetChat] An error occurred during build

### ISSUE THREAD

**Issue by ranzeng** [android/compose-samples#439]
An exception occurred applying plugin request [id: 'com.android.application']
> Failed to apply plugin 'com.android.internal.application'.
   > java.util.concurrent.ExecutionException: java.lang.NoSuchMethodException: java.lang.invoke.MethodHandles.privateLookupIn(java.lang.Class, java.lang.invoke.MethodHandles$Lookup)

**Comment by supermar1010** [comment]
I had the same problem then I read the readme :D 
It says to use the latest canary build of Android Studio

**Comment by lim4th3us** [comment]
@supermar1010 even using most recent canary (4.2 beta 6), and using `com.android.tools.build:gradle:7.0.0-alpha10` i received this error: 

> This version of the Android Support plugin for IntelliJ IDEA (or Android Studio) cannot open this project, please retry with version 4.3 or newer.

i needed to use `com.android.tools.build:gradle:4.2.0-beta06` to build JetChat

**Comment by jsonhu** [comment]
try to replace your project jdk1.8 to jdk11

**Comment by jiao08** [comment]
> try to replace your project jdk1.8 to jdk11
Yes, this is the correct answer!

**Comment by fmliqi** [comment]
> try to replace your project jdk1.8 to jdk11

nothing for help
