### ISSUE TITLE
Dark theme does not seem comfortable. What can I do?

### ISSUE THREAD

**Issue by halilozel1903** [android/compose-samples#442]
Hello everyone,

I started Jetpack Compose 🥳 but My Android Studio has Dark theme. Elements are not read when I preview.

<img width="868" alt="Screen Shot 2021-03-15 at 4 06 25 PM" src="https://user-images.githubusercontent.com/22895813/111157850-69be2100-85a8-11eb-83f8-cedacf143cc5.png">

How can I prevent this?

I would be glad if you could help.

**Comment by GGorAA** [comment]
You can add `showBackground = true` argument to @Preview annotation

**Comment by nickbutcher** [comment]
Closing as this is not an issue with the samples in this repo and would be better suited for [Slack](http://slack.kotlinlang.org/)/[StackOverflow](https://stackoverflow.com/questions/tagged/android-jetpack-compose).
