### ISSUE TITLE
[Jetsnack/Owl] Simultaneous taps navigate multiple times 

### ISSUE THREAD

**Issue by alexvanyo** [android/compose-samples#456]
This affects both Jetsnack (not using androidx.navigation) and Owl (is using androidx.navigation).

If multiple items are tapped at the same time, 2 or more detail screens can be launched. This isn't necessarily a uniquely Jetpack Compose issue, as this plagues a lot of non-Jetpack Compose apps, but I'd be very interesting to see what the "correct" way to handle it is in the Compose world.

Jetsnack:

https://user-images.githubusercontent.com/4217560/113164235-898b5100-9206-11eb-829d-ec695137ff42.mp4

Owl:

https://user-images.githubusercontent.com/4217560/113164266-91e38c00-9206-11eb-9f55-acdf98dda434.mp4

**Comment by JoseAlcerreca** [comment]
Great catch. I uploaded a solution to

https://github.com/JoseAlcerreca/compose-samples/pull/new/owl_multiple_nav_fix

You could also check `LocalLifecycleOwner.current.lifecycle.currentState.isAtLeast(Lifecycle.State.RESUMED)` inside the composable destination before using the callback.

**Comment by alexvanyo** [comment]
Thanks for the response! I was exploring potential solutions a bit myself, and for comparison I wanted to share an idea I came up with:

https://github.com/android/compose-samples/compare/main...alexvanyo:av/token-based-navigation

The rough idea I had was to associate a navigation "action" (a lambda that will ultimately perform `.navigate()` when invoked) with a token that marks where/when the "action" was composed. Then the deduplication logic for an action could just be a check on whether the current, up-to-date token matches the token that is tagged with the action. In this case, I made the token be a UUID that is updated anytime the backstack changes.

I also took a stab at making that a bit more general here:

https://github.com/android/compose-samples/compare/main...alexvanyo:av/tokenized-nav-controller

In theory that "token" could be anything: a UUID, the current route, an appropriate sealed class, or some alternate representation of the full backstack. With a `TokenPolicy`, actions can specify when they should run (based on the current token), and then update the token if they do.

**Comment by alexvanyo** [comment]
Closing this issue, checking the `lifecycle` of the `NavBackStackEntry` nicely allows removing simulatenous taps:

```kotlin
/**
 * If the lifecycle is not resumed it means this NavBackStackEntry already processed a nav event.
 *
 * This is used to de-duplicate navigation events.
 */
private fun NavBackStackEntry.lifecycleIsResumed() =
    this.lifecycle.currentState == Lifecycle.State.RESUMED
```
