### ISSUE TITLE
How to integrate the autofill framework in a compose app

### ISSUE THREAD

**Issue by ln-12** [android/compose-samples#473]
I want to integrate the [autofill framework](https://developer.android.com/guide/topics/text/autofill-optimize) in my compose app. I see that there is a [compose autofill package](https://developer.android.com/reference/kotlin/androidx/compose/ui/autofill/package-summary), but I can't find any documentation on how to set `autofillHints` for the text fields. How would I do that? Is this even possible right now?

**Comment by adrinieto** [comment]
I've found this[ blog post](https://bryanherbst.com/2021/04/13/compose-autofill/) that explains how to integrate it.

**Comment by JoseAlcerreca** [comment]
Thanks for taking the time to open an issue! As this is not related to the Compose samples, you might want to try posting it on sites such as stackoverflow.

**Comment by ln-12** [comment]
@adrinieto I tried out the post you mentioned, but I can't get a single popup to show.

@JoseAlcerreca  I thought it would be a great idea to provide a basic sample that demonstrates the correct usage.
