### ISSUE TITLE
 very slow run

### ISSUE THREAD

**Issue by flashiran1** [android/compose-samples#48]
hi
the my phone this project (JetNews) very slow run

Background sticky concurrent mark sweep GC freed 43281(2MB) AllocSpace objects, 24(432KB) LOS objects, 3% free, 48MB/50MB, paused 5.623ms total 69.124ms

my phone huawei ascend p7
api 21

**Comment by nickbutcher** [comment]
Jetpack Compose is in Developer Preview and performance has not been a focus so far.

**Comment by hosseinkhojany** [comment]
why? /:
