### ISSUE TITLE
[Crane] Couldn't inline method call 'Row' into @androidx.compose.runtime.Composable

### ISSUE THREAD

**Issue by CMingTseng** [android/compose-samples#480]
org.jetbrains.kotlin.codegen.CompilationException: Back-end (JVM) Internal error: Couldn't inline method call 'Row' into
@androidx.compose.runtime.Composable 

private fun MonthHeader(modifier: androidx.compose.ui.Modifier = ..., month: kotlin.String, year: kotlin.String): kotlin.Unit defined in androidx.compose.samples.crane.calendar in file Calendar.kt

@Composable
private fun MonthHeader(modifier: Modifier = Modifier, month: String, year: String) {
    Row(modifier = modifier) {
        Text(
            modifier = Modifier.weight(1f),
            text = month,
            style = MaterialTheme.typography.h6
        )
        Text(
            modifier = Modifier.align(Alignment.CenterVertically),
            text = year,
            style = MaterialTheme.typography.caption
        )
    }
}

Cause: Not generated
File being compiled: (79,5) in  

Crane/app/src/main/java/androidx/compose/samples/crane/calendar/Calendar.kt

The root cause java.lang.IllegalStateException was thrown at: org.jetbrains.kotlin.codegen.inline.InlineCodegen$Companion.getCompiledMethodNodeInner(InlineCodegen.kt:596)
	at org.jetbrains.kotlin.codegen.inline.InlineCodegen.throwCompilationException(InlineCodegen.kt:105)

**Comment by riggaroo** [comment]
Thanks for the bug report!

Could you please provide more information:

* Which sample app you are experiencing this crash on? Are you still experiencing this issue? We are going through cleanup of the issues here. 
* Android Version 
* Compose Version 
* Kotlin version
* Steps to reproduce the issue
Thanks!

**Comment by riggaroo** [comment]
Closing as inactive and unable to reproduce
