### ISSUE TITLE
[Jetsurvey] Could not find androidx.compose:compose-compiler:1.0.0-beta05

### ISSUE THREAD

**Issue by CMingTseng** [android/compose-samples#481]
Dear Sir

I clone and build

it show  

   > Could not find androidx.compose:compose-compiler:1.0.0-beta05.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/androidx/compose/compose-compiler/1.0.0-beta05/compose-compiler-1.0.0-beta05.pom
       - https://repo.maven.apache.org/maven2/androidx/compose/compose-compiler/1.0.0-beta05/compose-compiler-1.0.0-beta05.pom
       - https://jcenter.bintray.com/androidx/compose/compose-compiler/1.0.0-beta05/compose-compiler-1.0.0-beta05.pom
     Required by:
         project :app 
         
         I  ref this page   https://developer.android.com/jetpack/androidx/releases/compose
         
         1.0.0-beta05  release   
         
         THX

**Comment by tobiraak** [comment]
Did you find a solution to this? I am still getting this error

**Comment by phongbm** [comment]
I found that solution, it worked for me.
https://stackoverflow.com/a/65590130/5187940

**Comment by noktigula** [comment]
Still getting this error, the trick with adding configurations didn't work for me

**Comment by phongbm** [comment]
> 
> 
> Still getting this error, the trick with adding configurations didn't work for me

Are you sure block configurations{} above kotlin{}?

**Comment by IanGClifton** [comment]
This should be fixed with the updated dependencies.
