### ISSUE TITLE
[Crane] Return type of 'create' is not a subtype of the return type of the overridden member

### ISSUE THREAD

**Issue by CMingTseng** [android/compose-samples#482]
@

Crane\android\src\main\java\androidx\compose\samples\crane\details\DetailsViewModel.kt: (49, 73) 

Return type of 'create' is not a subtype of the return type of the overridden member 'public abstract fun <T : ViewModel!> create(p0: Class<(T#1 (type parameter of androidx.lifecycle.ViewModelProvider.Factory.create)..T#1?)>): T#1!! defined in androidx.lifecycle.ViewModelProvider.Factory'

**Comment by riggaroo** [comment]
This should be resolved by switching to Hilt.
