### ISSUE TITLE
BasicTextField can add a parameter to always hide the keyboard

### ISSUE THREAD

**Issue by jicg** [android/compose-samples#485]
BasicTextField can add a parameter to always hide the keyboard

![image](https://user-images.githubusercontent.com/6479672/115999877-48793780-a620-11eb-8ead-0d222a2a4ba5.png)
```java
if(xxxx)
    textInputSession.showSoftwareKeyboard()
```

**Comment by JoseAlcerreca** [comment]
Thanks for taking the time to open an issue! As this is not related to the Compose samples, you might want to try posting it on sites such as stackoverflow.
