### ISSUE TITLE
android studio support plugin

### ISSUE THREAD

**Issue by rezajax** [android/compose-samples#504]
I am using Android Studio 4.1.3, but I get this error when I run

This version of the Android Support plugin for IntelliJ IDEA (or Android Studio) cannot open this project, please retry with version 2020.3.1 or newer.

**Comment by hfhbd** [comment]
You do need Android Studio Canary 2020.3.1

**Comment by CMingTseng** [comment]
you can use this gradle  ( only use compose  can not preview @IDE )

https://github.com/CKS-ROC/Useful_Gradle/blob/master/config_preuse_compose.gradle

apply from: 'https://raw.githubusercontent.com/CKS-ROC/Useful_Gradle/master/config_preuse_compose.gradle'

the reason can 

https://marcellogalhardo.dev/posts/2021/03/30/using-compose-beta-on-as-4-1/

and 

this demo project 

https://github.com/joreilly/PeopleInSpace/blob/da0f6695d99208245abdba08417e038eff568071/app/build.gradle.kts#L49
