### ISSUE TITLE
Invalid injected android support version '202.7660.26.42.7322048', expected to be of the form 'w.x.y.z' [SOLVED: Use Arctic Fox]

### ISSUE THREAD

**Issue by xiaohaixiangqianchong** [android/compose-samples#507]
My android studio version is 4.2.0 ,Detail info is below:
Android Studio 4.2
Build #AI-**202.7660.26.42.7322048**, built on April 29, 2021
Runtime version: 11.0.8+10-b944.6842174 amd64
VM: OpenJDK 64-Bit Server VM by N/A

how to fix this problem？Thanks。

**Comment by kimljx** [comment]
I have the same problem .

**Comment by nysin** [comment]
i get the same problem

**Comment by gabrielemariotti** [comment]
Use AS in canary: Android Studio Arctic Fox | 2020.3.1 Canary 15

**Comment by tienthanh2509** [comment]
I have the same problem

```
Android Studio 4.2
Build #AI-202.7660.26.42.7322048, built on April 29, 2021
Runtime version: 11.0.8+0-b944-P17168821 amd64
VM: OpenJDK 64-Bit Server VM by N/A
Linux 5.4.0-72-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry: external.system.auto.import.disabled=true
Non-Bundled Plugins: Dart, org.jetbrains.kotlin, io.flutter, org.intellij.plugins.markdown
Current Desktop: X-Cinnamon

Invalid injected android support version '202.7660.26.42.7322048', expected to be of the form 'w.x.y.z'

```

**Comment by ChiaYang1** [comment]
Should download AS with canary channel.
 [See Here](https://stackoverflow.com/questions/67447249/import-compose-sample-projects-to-android-studio-version-4-2)

### Two way:
1. Perferences -> Appearance & Behavior -> System setting -> Update -> Choose "Canary channel" -> Check now
 
<img width="1001" alt="截圖 2021-05-17 上午11 01 24" src="https://user-images.githubusercontent.com/70250649/118427326-850bf080-b6ff-11eb-804b-6e6d79c14e2e.png">

2. go to [download-canary dircectly](https://developer.android.com/r/studio-ui/download-canary.html)
