### ISSUE TITLE
[Jetchat]聊天功能异常（The chat function is abnormal）

### ISSUE THREAD

**Issue by Vicent9920** [android/compose-samples#508]
* 关闭软键盘，页面不能自动刷新
 * Turn off the soft keyboard, the page will not refresh automatically
  ![QQ图片20210507182406](https://user-images.githubusercontent.com/17283445/117436367-7dab5100-af61-11eb-8738-3c39825e804e.png)
 * 消息发送以后，本地消息未刷新
 * After the message is sent, the local message is not refreshed

**Comment by NickGuaGua** [comment]
The new message is shown at the top of the list. You can modify the compose component `Message` to show the newest message at the bottom of the list.

**Comment by JoseAlcerreca** [comment]
#596
