### ISSUE TITLE
[Jetsurvey] App crash on changing selected data in date selection question (question 4)

### ISSUE THREAD

**Issue by Abhimanyu14** [android/compose-samples#512]
The app crashed when I tried to change the selected date for the date selection question.

Question: "When was the last time you ordered a takeaway ..."

https://user-images.githubusercontent.com/29737108/117548139-df96b400-b050-11eb-8d0c-cb09874080aa.mp4

**Comment by IanGClifton** [comment]
Looks like your fix was merged but this issue didn't get closed out, so closing it now. Thanks!
