### ISSUE TITLE
App Crash on text update in Activity File

### ISSUE THREAD

**Issue by QumberAbbas12** [android/compose-samples#519]
When the app is in the foreground and I update the text in setContent. App gets crashed

```
class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            Greeting("Hello World")
        }
    }
}

@Composable
fun Greeting(text: String) {
    Text(text = text, color = Color.White)
}


```

2021-05-12 02:35:28.369 22759-22759/com.dev.composetraining A/composetrainin: runtime.cc:663] JNI DETECTED ERROR IN APPLICATION: JNI CallVoidMethodV called with pending exception java.lang.NoSuchMethodError: no non-static method "Landroidx/compose/runtime/HotReloader$Companion;.saveStateAndDispose(Ljava/lang/Object;)V"
    runtime.cc:663]   at void dalvik.system.VMDebug.nativeAttachAgent(java.lang.String, java.lang.ClassLoader) (VMDebug.java:-2)
    runtime.cc:663]   at void dalvik.system.VMDebug.attachAgent(java.lang.String, java.lang.ClassLoader) (VMDebug.java:572)
    runtime.cc:663]   at boolean android.app.ActivityThread.attemptAttachAgent(java.lang.String, java.lang.ClassLoader) (ActivityThread.java:3928)
    runtime.cc:663]   at void android.app.ActivityThread.handleAttachAgent(java.lang.String, android.app.LoadedApk) (ActivityThread.java:3938)
    runtime.cc:663]   at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:2054)
    runtime.cc:663]   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:106)
    runtime.cc:663]   at void android.os.Looper.loop() (Looper.java:223)
    runtime.cc:663]   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:7660)
    runtime.cc:663]   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
    runtime.cc:663]   at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:592)

**Comment by JoseAlcerreca** [comment]
Not related to samples.
Thanks for taking the time to open an issue! As this is not related to the Compose samples, you might want to try posting it on sites such as stackoverflow.
