### ISSUE TITLE
[Jetchat] Confused on "Back button handling"

### ISSUE THREAD

**Issue by wjploop** [android/compose-samples#528]
I am confused about the code below
```Kotlin
ProvideWindowInsets(consumeWindowInsets = false) {
                    ...
                    // Intercepts back navigation when the drawer is open
                    val scope = rememberCoroutineScope()
                    if (scaffoldState.drawerState.isOpen) {
                        BackPressHandler {
                            scope.launch {
                                scaffoldState.drawerState.close()
                            }
                        }
                    }
                  
                  JetchatScaffold ...

```
The composable `BackPressHandler` seems to be inserted or removed when the drawer state changed, which is not intuitive.

I think the `BackPressHandler` should be the parent of `JetchatScaffold`  and provide a Lamda as a parameter to its child ask if there any children want to consume the back event.

**Comment by JoseAlcerreca** [comment]
Why create an extra BackPressHandler with an if statemente instead of simply removing it from the hiearchy?
