### ISSUE TITLE
Cannot find Rally screenshots when golden image tests fail

### ISSUE THREAD

**Issue by fmatosqg** [android/compose-samples#533]
According to `ScreenshotComparator` files should be available after `AnimatingCircleTest` runs:

However I can't seem to find such files on either physical phone or emulator.

Assuming there was a regression bug introduced in Rally code and tests are written correctly, what's the best way to troubleshoot Rally code and compare expected screenshot against actual screenshot?

```

private fun saveScreenshot(filename: String, bmp: Bitmap) {
    val path = InstrumentationRegistry.getInstrumentation().targetContext.filesDir.canonicalPath
    FileOutputStream("$path/$filename.png").use { out ->
        bmp.compress(Bitmap.CompressFormat.PNG, 100, out)
    }
    println("Saved screenshot to $path/$filename.png")
}
```

By the way, printing "$path/$filename.png" gives something like `/data/data/com.example.compose.rally/files/circle_initial1621298229665.png`, but `/data/data/com.example.compose.rally` is never created

Edit: seems like running tests from Android Studio leaves the files/folders in place, but running from command line erases the folder and the application once the test is finished.

**Comment by JoseAlcerreca** [comment]
The screenshot comparator is not meant to be used in production, just a way to showcase the time-related test APIs.

From https://developer.android.com/studio/debug/device-file-explorer ->

Note: Most device data is not visible unless you are using a rooted device or an emulator with a standard Android (AOSP) system image (not one of the Google APIs or Google Play system images). And when using a connected device, be sure you enable USB debugging.
