### ISSUE TITLE
[Jetnews] Swipe-to-refresh progress indicator does not change opacity as the component transitions into view

### ISSUE THREAD

**Issue by c5inco** [android/compose-samples#541]
Swipe-to-refresh progress indicator does not change opacity as the component transitions into view

Proposed solution: Swipe-to-refresh progress indicator should fade in from 0% to 100% as it approaches its placement. See behavior at https://material.io/design/platform-guidance/android-swipe-to-refresh.html#behavior-placement.

Opacity should be driven by the swipe % complete.

Currently we are using the SwipeRefresh indicator from the Accompanist library. I think it would be great to get the polish done at first through a [custom indicator](https://google.github.io/accompanist/swiperefresh/#indicator)

**Comment by c5inco** [comment]
@angeles-bilbao6 will work on this per my conversation with @JolandaVerhoef

**Comment by c5inco** [comment]
@chrisbanes do you think this something we should instead fix in Accompanist? I see at the moment in your source for the `SwipeRefreshIndicator` that the transition goes from `0.3f` to `1f` based on a state change in the transition and is not necessarily tied to drag offset progress.

What do you think?

**Comment by chrisbanes** [comment]
Yeah I think this sounds like something we should fix in Accompanist. I’ll add a bug to track
