### ISSUE TITLE
Set `develop` branch as default branch for repo

### ISSUE THREAD

**Issue by burntcookie90** [android/compose-samples#55]
Currently, JetNews is more or less the source of truth on using jetpack compose. When you first get to this repository you land on master, which is currently _very_ out of date (in the compose world). It would be far more useful to folks for `develop` to be the default branch for viewing to reduce confusion.

**Comment by burntcookie90** [comment]
For the record: i only realized the `develop` branch existed thanks to nick's reply to another tweet here https://twitter.com/crafty/status/1232668784680427520

**Comment by nickbutcher** [comment]
Ideally `master` wouldn't be so out of date but we had some issues with `dev04`. We should be updating to `dev05` shortly.

Would being up to date with the latest `devXX` release **plus** something in the README calling out the `develop` branch help?

**Comment by burntcookie90** [comment]
Yes, I think that would work as well. However, with `develop` working off of `SNAPSHOT` builds, could this cause delays in keeping `master` up to date with `devXX` builds?

**Comment by DolphinWing** [comment]
The sample is now dev06.
