### ISSUE TITLE
The project is using an incompatible version (7.0.0-beta01) of the Android Gradle plugin.

### ISSUE THREAD

**Issue by boldijar** [android/compose-samples#552]
I want to start learning compose but I always get this error.

The project is using an incompatible version (7.0.0-beta01) of the Android Gradle plugin.

I have the latest android studio, canary version

Android Studio Bumblebee | 2021.1.1 Canary 1
Build #AI-203.7717.56.2111.7361063, built on May 14, 2021
Runtime version: 11.0.10+0-b96-7281165 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.7
GC: G1 Young Generation, G1 Old Generation
Memory: 1280M
Cores: 4
Registry: external.system.auto.import.disabled=true
Non-Bundled Plugins: org.jetbrains.kotlin

And I cannot upgrade the project.
The Upgrade Assistant failed to upgrade this project, finding no way of performing the Upgrade AGP version from 7.0.0-beta01 to 7.1.0-alpha01 command, possibly because the project's build files use features not currently supported by the Upgrade Assistant (for example: using constants defined in buildSrc, or other unrecognized constructs, in Gradle build files).

I had this issue for other demos as well, and is a bit frustrating.

I saw that  solution would be to downgrade some gradle version in the dependencies, but why is that? Shouldn't the project work with the default configuration?

**Comment by jpujolji** [comment]
posible duplicate #337

**Comment by JoseAlcerreca** [comment]
Samples (as of writing) are compatible with the latest Arctic Fox release, which uses AGP 7.0. 

Bumblebee uses AGP 7.1 so you can upgrade to it manually (the automatic updater doesn't work when you use variables) or download AF (preferred).
