### ISSUE TITLE
[JetCaster] Feed rendering issues

### ISSUE THREAD

**Issue by michal-luszczuk** [android/compose-samples#553]
1. Open JetCaster app
2. Scroll 'fling' podcasts main feed up and down randomly
3. Rows representing specific podcast are not rendering properly

Screenshot (device: Pixel 5, Android 11) :
![image](https://user-images.githubusercontent.com/9006071/120083928-7c86c300-c0cc-11eb-8220-46818a4f86f3.png)

Layout inspector (Arctic Fox 2020.3.1 beta 3):
![image](https://user-images.githubusercontent.com/9006071/120083939-90cac000-c0cc-11eb-9f4e-5f34d2a81090.png)

Video:

https://user-images.githubusercontent.com/9006071/120083991-ef903980-c0cc-11eb-8e38-d575a8d6e3aa.mp4

**Comment by p2LEm8** [comment]
This issue caused due to constraint layout that is in alpha. Replace it with columns/rows and everything will work fine.
