### ISSUE TITLE
[JetChat] Blank page after keyboard appears

### ISSUE THREAD

**Issue by Macrox14** [android/compose-samples#554]
Blank page after keyboard appears
1. Open App
![Screenshot_1622403105](https://user-images.githubusercontent.com/31378074/120117794-86540900-c154-11eb-81c2-d93100229e48.png)
2. Click on textfield
![Screenshot_1622403154](https://user-images.githubusercontent.com/31378074/120117797-8c49ea00-c154-11eb-8a5f-468b5261961c.png)
3. Click on picture of the girl
![Screenshot_1622403179](https://user-images.githubusercontent.com/31378074/120117799-8eac4400-c154-11eb-89c3-286a98a6fee7.png)
PS: Testing in emulated Pixel 2

**Comment by JoseAlcerreca** [comment]
I can easily reproduce, this seems like a regression.

Layout inspector only shows the empty nav_host_fragment
![image](https://user-images.githubusercontent.com/609125/121696130-09b61880-cacc-11eb-8ec8-e9b29090ded9.png)

Even with the blank screen, you can drag the drawer out:
![image](https://user-images.githubusercontent.com/609125/121696267-2fdbb880-cacc-11eb-8360-e446e8d196b0.png)

Clicking on any of the items on the drawer closes the drawer but still shows a blank screen.

**Comment by JoseAlcerreca** [comment]
- Using a debugger we can see that the fragment, viewmodel and profile composables are hit and should be rendering content.
 - Sometimes the profile is navigated to correctly but the screen is blank after navigating back.

This could have been introduced with the fix for https://issuetracker.google.com/175864912

**Comment by JoseAlcerreca** [comment]
Seems to not repro on API 30, but it does on 28, 29.

**Comment by JoseAlcerreca** [comment]
This was fixed in rc01
