### ISSUE TITLE
[Jetcaster] - PodcastCategoryViewModel is not cleared properly

### ISSUE THREAD

**Issue by ynkm169** [android/compose-samples#564]
When you create viewmodel using the activity as scope, it means it is only cleared when activity goes away.
Imagine you have 100 categories, when you switch different categories 100 times, the viewmodel is created 100 times for different categories. 100 view models are cleared only when activity goes away. I debugged they are not cleared when you switch categories.

Is there anyway to easily clear the current category viewmodel when the category is switched? 
(I know you can create your own viewmodelstore and manually destroy viewmodels in it but that doesn't sound like an intuitive solution)

I know not destroying the viewmodel kinda cache it in memory, but...

1. when you switch category, you probably want to retrieve latest data anyway, so not much reason to cache it.
2. In a single activity app, the user might never "quit" the app, so you just keep creating view models and they remain in memory, potentially "hot", and actively doing work.

```
@Composable
fun PodcastCategory(
    categoryId: Long,
    modifier: Modifier = Modifier
) {   

 val viewModel: PodcastCategoryViewModel = viewModel(
        // We use a custom key, using the category parameter
        key = "category_list_$categoryId",
        factory = viewModelProviderFactoryOf { PodcastCategoryViewModel(categoryId) }
    )
}
```

**Comment by alanwgeorge** [comment]
@ynkm169 I maybe wrong here but in the context of a NavHost, isn't the ViewModel store provider the backstack entry and not the Activity?  So ViewModels will get cleaned up on back nav?
