### ISSUE TITLE
matchParentSize() and fillMaxSize()

### ISSUE THREAD

**Issue by LloydFinch** [android/compose-samples#583]
why matchParentSize() only can use in Box{}

**Comment by nickbutcher** [comment]
Per the [reference doc](https://developer.android.com/reference/kotlin/androidx/compose/foundation/layout/BoxScope#(androidx.compose.ui.Modifier).matchParentSize()):

"In contrast, a general-purpose Modifier.fillMaxSize modifier, which makes an element occupy all available space, will take part in defining the size of the Box. Consequently, using it for an element inside a Box will make the Box itself always fill the available space."
