### ISSUE TITLE
Preview stop working after 1.0.0-rc01

### ISSUE THREAD

**Issue by lfgtavora** [android/compose-samples#592]
After update ui-tooling from beta09 to 1.0.0-rc01 we are facing a render problem, @previews cant render anymore, besides still running perfectly on emulator. Reading the documentation, i found some curious:

> Split ui-tooling module into ui-tooling and ui-tooling-preview (Iefa28, b/190649014)

so that i tried to implement tooling-preview import but the render problems still happening... if i come back to beta09 works fine, anyone facing same problem?

>     implementation("androidx.compose.ui:ui-tooling:1.0.0-rc01")

<img width="500" alt="Captura de Tela 2021-07-02 às 16 47 44" src="https://user-images.githubusercontent.com/44548041/124325790-ab74d680-db5b-11eb-94b4-6663af90f8d2.png">
<img width="523" alt="Captura de Tela 2021-07-02 às 16 48 10" src="https://user-images.githubusercontent.com/44548041/124325798-b0d22100-db5b-11eb-82ce-4850c915f385.png">

**Comment by wiryadev** [comment]
i got this too, both in samples and my own project

**Comment by bodoss** [comment]
the same.

**Comment by Softtanck** [comment]
The same. (⊙︿⊙)

**Comment by wiryadev** [comment]
https://issuetracker.google.com/issues/192686337

opened an issue on issuetracker, with reference link to this thread

**Comment by amaurymedeiros** [comment]
Please keep an eye on https://issuetracker.google.com/issues/192570889.

Everything should work just fine in Arctic Fox RC01. This release was initially planned to ship with Compose 1.0 RC01, but the timeline shifted a bit.
