### ISSUE TITLE
[Jetcaster] App is very laggy on scrolling list

### ISSUE THREAD

**Issue by hosseinkhojany** [android/compose-samples#599]
Jetcaster is very laggy when scrolling list

**Comment by wiryadev** [comment]
mine is fine, no lag, using AF Beta 5

**Comment by muhammadalkady** [comment]
It is also very laggy on Xiaomi Mi A2 even in release mode.

**Comment by JoseAlcerreca** [comment]
Performance of debug builds is a problem right now. R8 does some optimizations but you're still running in interpreted mode (to my limited understanding). We hope to have tooling to let us do performance tests correctly at some point.

For a complete explanation, Leland goes into detail here: https://www.twitch.tv/videos/1122138667?t=01h21m40s

**Comment by muhammadalkady** [comment]
@JoseAlcerreca It slow also in release mode

**Comment by JoseAlcerreca** [comment]
Yes, that's what I'm saying.

**Comment by muhammadalkady** [comment]
Any solutions to these performance issues ?!
I have enabled R8, shrinking resources, and optimized progurad-rules and LazyColumn still lags with the simplest examples.
