### ISSUE TITLE
onBackPressed not working as expected

### ISSUE THREAD

**Issue by webianks** [android/compose-samples#6]
onBackPressed() from ArticleScreen closes app instead of navigating back to Home screen. From navigationIcon it works as intended.

**Comment by webianks** [comment]
Will this work?

 override fun onBackPressed() {
        if (JetnewsStatus.currentScreen != Screen.Home) {
            navigateTo(Screen.Home)
        } else
            super.onBackPressed()
    }

**Comment by nickbutcher** [comment]
Thanks for the suggestion. We considered adding something like this but did not want to complicate the navigation by adding a back stack. A proper navigation solution is on the roadmap and we did not want to imply that developers will need to roll their own so tried to keep this to the simplest possible solution.

Thanks again.
