### ISSUE TITLE
[Crane] Avoid useless mapInitial in MapViewContainer

### ISSUE THREAD

**Issue by MarcelReiter** [android/compose-samples#602]
I've been trying to understand Cranes Map and fell over the following code in File `DetailsActivity`:

 ```@Composable
private fun MapViewContainer(
    map: MapView,
    latitude: String,
    longitude: String
) {
    
    [...]

    var mapInitialized by remember(map) { mutableStateOf(false) }
    LaunchedEffect(map, mapInitialized) {
        if (!mapInitialized) {
            val googleMap = map.awaitMap()
            googleMap.addMarker { position(cameraPosition) }
            googleMap.moveCamera(CameraUpdateFactory.newLatLng(cameraPosition))
            mapInitialized = true
        }
    }

    [...]

}
```

If i understand `LaunchedEffect` and `mapInitialized` correctly, this code is completely equivalent:

```
LaunchedEffect(map) {
    val googleMap = map.awaitMap()
    googleMap.addMarker { position(cameraPosition) }
    googleMap.moveCamera(CameraUpdateFactory.newLatLng(cameraPosition))
}
```

If my understanding is correct, would you please update the sample with my easier code?
I guess it will be copied into countless projects, since it's the only official map sample i'm aware of.

If it is not correct, could you elaborate why?

**Comment by JoseAlcerreca** [comment]
I assume this has to do with dealing with different lifecycles, but it should be explained in the code.

**Comment by manuelvicnt** [comment]
Yeah, this can be simplified! Thanks for noticing. Fix on its way
