### ISSUE TITLE
Duplicate resources issue

### ISSUE THREAD

**Issue by PemmasaniRajesh** [android/compose-samples#621]
When I'm trying to use images from mipmap folder, it's giving duplicate resources issue. I've created app launcher icon using Image Asset. We all know Compose only supports the resources like rasterized images (ex. PNG or JPG files) or VectorDrawable xml assets. 

Anyone faced an issue like this ? I've solved this by creating a copy of image and put it in drawable folder. 

So in JetPack Compose, there should not be multiple resources for different screens is it ?

![image](https://user-images.githubusercontent.com/10286949/128660771-90011249-76e9-4849-882e-7ccc832a4096.png)

**Comment by nickbutcher** [comment]
Compose doesn't change the need to provide alternate resources for differnet screen densities. What error are you seeing. I'll close this issue and it's not an issue with the samples in this repo and better suited to [StackOverflow](https://stackoverflow.com/questions/tagged/android-jetpack).
