### ISSUE TITLE
[Jetcaster] Bug swiping HorizontalPager in Home Screen crashes app 

### ISSUE THREAD

**Issue by abdalla-hassanin** [android/compose-samples#627]
### when swiping HorizontalPager in Home Screen crashed app and this appear :
`java.lang.IllegalArgumentException: Layout size for current item is 0
        at com.google.accompanist.pager.PagerState$scrollableState$1.invoke(PagerState.kt:182)`

[https://github.com/android/compose-samples/blob/main/Jetcaster/app/src/main/java/com/example/jetcaster/ui/home/Home.kt#L181](url) In this line I solved the error by placing `if (featuredPodcasts.isNotEmpty()) featuredPodcasts.size else 1`

Is this a good solution?

**Comment by JoseAlcerreca** [comment]
@chrisbanes is this what you were fixing last week?

**Comment by chrisbanes** [comment]
Yeah, pretty sure this will be fixed in the latest releases.
