### ISSUE TITLE
Safe way to collect flows in compose

### ISSUE THREAD

**Issue by rubenquadros** [android/compose-samples#642]
According to @manuelvicnt article you could waste resources by collecting flows when the app is in background.
https://medium.com/androiddevelopers/a-safer-way-to-collect-flows-from-android-uis-23080b1f8bda#27a9
But none of the samples follow this.
What is the ideal way to collect flows in a composable?

**Comment by LeMimit** [comment]
Hello ! 

This is a pretty good question. I was wondering the real difference between using `rememberFlowWithLifecycle` or not in addition of `collectAsState` to collect a ` StateFLow` in Compose.

```kotlin
val availableThemes by rememberFlowWithLifecycle(viewModel.availableThemes).collectAsState(listOf())
vs
val availableThemes by viewModel.availableThemes.collectAsState()
```

There are two implementations. In https://github.com/google/iosched `rememberFlowWithLifecycle` is used but not in the examples in this repository.

Is it possible to have guidance or explanation of the differences ?

Thanks a lot !

**Comment by dilraj-singh1997** [comment]
Yup very legit question

**Comment by manuelvicnt** [comment]
Hi there! The same guidance we have for Views applies to Compose. We'll need to update our samples to use something like `rememberFlowWithLifecycle`. 

When a Compose app is in the background, recompositions are scheduled but they aren't triggered until the host is STARTED again. Even if this might not be an issue in Compose, the problems could come with flow producers being active in the background.

**Comment by LeMimit** [comment]
Thanks for the answer @manuelvicnt !

**Comment by mickael-menu** [comment]
The samples are still not using `rememberFlowWithLifecycle` or `flowWithLifecycle`. Was this issue addressed differently?
