### ISSUE TITLE
Gradle sync failed: Unsupported method: IdeaContentRoot.getGeneratedSourceDirectories().

### ISSUE THREAD

**Issue by sunyongsheng** [android/compose-samples#651]
I clone the project and import into Android Studio, and then got a fail while gradle sync:

```
Gradle sync failed: Unsupported method: IdeaContentRoot.getGeneratedSourceDirectories().
			The version of Gradle you connect to does not support that method.
			To resolve the problem you can change/upgrade the target version of Gradle you connect to.
			Alternatively, you can ignore this exception and read other information from the model. (3 s 765 ms)
```

I didn't do anything.

![image](https://user-images.githubusercontent.com/38694647/132830349-57492edc-ea47-4c7c-911b-200b792d0fee.png)

My Android Studio version is:

Android Studio Arctic Fox | 2020.3.1 Patch 2
Build #AI-203.7717.56.2031.7678000, built on August 27, 2021
Runtime version: 11.0.10+0-b96-7281165 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.5.2
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 12
Registry: ide.instant.shutdown=false, external.system.auto.import.disabled=true, gradle.tooling.custom.serializer=false
Non-Bundled Plugins: cn.xiaoheiban.go-zero, com.bytedance.idea-tools.bytedance-plugin-store, com.bytedance.tools.wrangler, Dart, org.jetbrains.kotlin, io.flutter, com.bytedance.android.tool.console1, com.bytedance.creativex.android.tools.pmodule, com.bytedance.plugins.matrix, com.developerphil.adbidea, com.bytedance.pluginx, com.bytedance.tools.popview, izhangzhihao.rainbow.brackets

**Comment by sunyongsheng** [comment]
I re-install Android Studio Arctic Fox and open the project, the problem still exists. Because the issue [Gray Rectangles pop up without text and won't go away until I quit Arctic Fox!
](https://issuetracker.google.com/issues/196995042#) , I delete the Android Studio Arctic Fox and then **use Android Stuido Preview Bumblebee** to open the same project, the problem disappeared... I have opened project with Bumblebee before, but I remember there was a problem, and I am not sure weather Arctic Fox affects Bumblebee. I'll close the issue.

**Comment by iljh** [comment]
This may be related to the use of incompatible plugins with Android Studio latest stable version.

You can try to verify as follows.
1. Delete `~/Library/Application Support/Google/AndroidStudio2020.3`, since you use Android Studio 2020.3 in MacOS.
2. reopen Android Studio, check if the issue persists.

If the issue disappeared and still want to use the incompatible plugin, you can try enable the `gradle.tooling.custom.serializer`.
`Help` -> `Find Action` -> text input `Registry`.
