### ISSUE TITLE
Can't render properly on xiaomi pocophone f1 when dark mode is enabled

### ISSUE THREAD

**Issue by cemaltaskiran** [android/compose-samples#652]
Hello,

When I wanted to test the app on my phone colors and some icons could not render properly. I use xiaomi pocophone f1. It might be problem with jetpack compose. 

Device Info
Brand: Xiaomi
Model: Pocophone f1
MIUI version: MIUI Global 12.0.3
Android Version: 10
Dark Mode: Enabled

![1631268166193](https://user-images.githubusercontent.com/18674877/132837484-7f53652a-6560-48b9-9ce5-efee3a2956b6.jpg)
![1631268166199](https://user-images.githubusercontent.com/18674877/132837510-d4b2f8b7-6295-44e8-8ed2-f04fd28e14a7.jpg)

**Comment by jiangdashao** [comment]
MIUI’s dark mode uses a forced inversion algorithm.

You can use `View.isForceDarkAllowed = false` to disable the force inversion
