### ISSUE TITLE
[Jetcaster] Project does not build on Mac with Apple Silicon m1

### ISSUE THREAD

**Issue by jstarczewski** [android/compose-samples#666]
Current version pulled freshly from `main` branch does not build on Macbook Pro 13' M1. The solution is to simply bump Room Version to `2.4.0-alpha03` or higher, because according to the [release notes the problem has been already solved](https://developer.android.com/jetpack/androidx/releases/room#2.4.0-alpha03). 

After bumping Room to `2.4.0-alpha04` which is the newest Alpha release it seems to works well, I can submit a pull request with described fix if needed :)

**Comment by IanGClifton** [comment]
Can anyone confirm if this issue is resolved (Jetcaster is on Room 2.4.2)?
