### ISSUE TITLE
[JetNews, JetSnack, Owl] The release version will crash if navigation-compose is used with minifyEnabled

### ISSUE THREAD

**Issue by yacca** [android/compose-samples#692]
When launching the release builds of Jetnews, Jetsnack, and Owl
the following crash occurs:

```
11-02 14:43:30.994 28787 28787 E AndroidRuntime: FATAL EXCEPTION: main
11-02 14:43:30.994 28787 28787 E AndroidRuntime: Process: com.example.owl, PID: 28787
11-02 14:43:30.994 28787 28787 E AndroidRuntime: java.lang.IllegalAccessError: Illegal class access: 'uu0$a' attempting to access 'androidx.navigation.compose.NavHostKt$PopulateVisibleList$1$1$observer$1' (declaration of 'uu0$a' appears in /data/app/~~NgrI5-Z5F9_KRcBP9LmPFA==/com.example.owl-bQbZtxrcUChvaK343C1SXw==/base.apk)
```

All these apps use navigation-compose and set minifyEnabled to true for release build.
My app also has the same issue.
But it works well when I use navigation-compose older than 2.4.0-alpha08.

**Comment by alexvanyo** [comment]
Thank you for the report, I can reproduce.

After investigating a bit, it appears this is an underlying R8 issue which only started occurring with changes added that were first released with `2.4.0-alpha09` to `navigation-compose`.

It looks that this has already been fixed on the R8 side, as updating to a later version of R8 prevents the crash for me:

```
buildscript {
    repositories {
        maven {
            url 'https://storage.googleapis.com/r8-releases/raw'
        }
    }
    dependencies {
        classpath 'com.android.tools:r8:3.1.34'          // Must be before the Gradle Plugin for Android.
        classpath 'com.android.tools.build:gradle:X.Y.Z' // Your current AGP version.
     }
}
```

Could you verify if updating R8 fixes the crash for your app?

**Comment by yacca** [comment]
@alexvanyo Thank you! That works for my app as well.

**Comment by alexvanyo** [comment]
Closing as obsolete

**Comment by alexvanyo** [comment]
Closing as obsolete
