### ISSUE TITLE
[Jetsurvey] Email TextField goes outside visible region

### ISSUE THREAD

**Issue by Abhimanyu14** [android/compose-samples#700]
On clicking Email `TextField` in the initial screen, the `TextField` is scrolled above the device display region.

Probable reason - Issues with small display size devices.

https://user-images.githubusercontent.com/29737108/140621077-e51656ce-5429-46ef-9ca7-f221c5fab7d0.mov

Device details - Xiaomi Redmi 4, Android 7.1.2, API 25

**Comment by raghunandankavi2010** [comment]
Yes i noticed this to. I don't think this has anything to do with device.

**Comment by tsuharesu** [comment]
Have been fixed by https://github.com/android/compose-samples/pull/779

**Comment by IanGClifton** [comment]
Thanks for calling that out, Tsuharesu!
