### ISSUE TITLE
Is there any plan to support Android TV and big screen devices? 

### ISSUE THREAD

**Issue by nasrabadiAM** [android/compose-samples#708]
As the stable version of compose just released, Is there any plan to add features for Android TV apps development? 
Or any sample available for any Android TV app using Jetpack compose?

**Comment by chainchelliah** [comment]
Any update?

**Comment by nasrabadiAM** [comment]
"Support Trackpad/D-Pad navigation" is currently in Jetpack compose roadmap. 

https://developer.android.com/jetpack/androidx/compose-roadmap

**Comment by c5inco** [comment]
We're in discussion with the Android TV team on adding Compose support in the future but have no concrete details at this time.

**Comment by florina-muntenescu** [comment]
Not an issue related to the samples

**Comment by markoeltiger** [comment]
they released it already you can check here 
[](https://youtu.be/MwHh8S7v_5E?t=86
)
