### ISSUE TITLE
Text selector detaches highlighted text when scrolling

### ISSUE THREAD

**Issue by michaellee8** [android/compose-samples#71]
version: fc789cb

Pictures say it all

![Screenshot_1586074651](https://user-images.githubusercontent.com/16556558/78470111-5d570480-7759-11ea-8ada-c9fa4cf204fe.png)
![Screenshot_1586074655](https://user-images.githubusercontent.com/16556558/78470113-5e883180-7759-11ea-8314-4f55eb1666b4.png)

**Comment by andre-vm** [comment]
I've got something related when long-clicking a drawer button:

![Peek 2020-06-13 20-14](https://user-images.githubusercontent.com/10947510/84581004-09991500-adb3-11ea-8046-cf70d8974cf0.gif)

**Comment by JoseAlcerreca** [comment]
Both issues are known and they're coming from the toolkit, not the sample itself. Thanks!
