### ISSUE TITLE
[JetChat] com.example.compose.jetchat.buildsrc.Libs in the build.gradle file doesn't resolve

### ISSUE THREAD

**Issue by mattcs2401** [android/compose-samples#721]
The line "import com.example.compose.jetchat.buildsrc.Libs" in the build.gradle file doesn't resove, unable to build.
Same for the .Urls and .Versions imports.
Followed the steps here: https://developer.android.com/jetpack/compose/setup

**Comment by xiaobo0528n** [comment]
I have same problem,please someone help us.
