### ISSUE TITLE
With a numeric keyboard, keeping down the delete button only deletes one character and then gets canceled (with this log: "IInputConnectionWrapper: sendKeyEvent on inactive InputConnection"):

### ISSUE THREAD

**Issue by Keldmar** [android/compose-samples#728]
I could reproduce the numeric keyboard case. With a numeric keyboard, keeping down the delete button only deletes one character and then gets canceled (with this log: "IInputConnectionWrapper: sendKeyEvent on inactive InputConnection"):

```
var textState by remember { mutableStateOf("") }
TextField(
    value = textState,
    onValueChange = {textState70 = it},
    keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Number),
)
```

_Originally posted by @Mbt925 in https://github.com/android/compose-samples/issues/364#issuecomment-1003432999_

**Comment by VadimB95** [comment]
Have this issue too. Seems like Jetpack Compose bug, but I haven't found something like this on the issue tracker.

**Comment by sanskar10100** [comment]
This is happening on using `KeyboardType.Password` too. Holding down the delete button only deletes one character, but on `KeyboardType.Text` the behaviour is normal.

**Comment by IanGClifton** [comment]
I filed https://issuetracker.google.com/228634682 to track this on the Compose side. I don't see anywhere in the Compose Samples where this issue is happening, so I'll close this, but please comment if I missed anything.
