### ISSUE TITLE
Data binding between different views

### ISSUE THREAD

**Issue by Zpecter** [android/compose-samples#75]
Hello,

Is there any way to bind or share variables between different composable functions?

Thanks

**Comment by AfzalivE** [comment]
@Zpecter I think creating a state outside of both functions and passing it as parameters would do it?

Not sure if that's the recommended way though.

**Comment by Zpecter** [comment]
> @Zpecter I think creating a state outside of both functions and passing it as parameters would do it?
> 
> Not sure if that's the recommended way though.

This is my declaration:

`var selectedDate : Date? by state { null }`
 
I have it declared into a composable function, if I put outside, it shows lots of errors, so I'm sending this value as a parameter to the other composable functions, but I got 2 errors:

1- Property delegate must have a 'setValue(Nothing?, KProperty<*>, Date?)' method. None of the following functions is suitable: 
public inline operator fun <T> MutableState<???>.setValue(thisObj: Any?, property: KProperty<*>, value: ???): Unit defined in androidx.compose
2 - Val cannot be reassigned

**Comment by AfzalivE** [comment]
(1) is due to missing imports. Try using auto-fix (alt/option + enter) while cursor is on the red line.
(2) Maaaybe same reason?

I saw these and they made no sense but then fixing the imports using auto-fix worked.

**Comment by nickbutcher** [comment]
Yes the answer to this question is state hoisting, to hold the state in a higher level component.
