### ISSUE TITLE
[Jetsurvey] When the Email composable is focused, the UI is pushed off screen

### ISSUE THREAD

**Issue by AllwinJohnson** [android/compose-samples#757]
Hi, 
First of all, Thank you for this wonderful code sample. 

**Issue**
The email editext in JetSurvey App goes offscreen while clicking in it. 
![image](https://user-images.githubusercontent.com/46625967/158995011-c6eb256b-d364-4155-be57-1f200da4a7fb.png)

**Comment by IanGClifton** [comment]
This appears to be caused by the onFocusChanged modifier in Email calling emailState.onFocusChange()
