### ISSUE TITLE
[Jetnews] Article BottomBar Buttons are too small to use

### ISSUE THREAD

**Issue by ed-george** [android/compose-samples#763]
Within the Article Screen of JetNews, the bottom bar's buttons are too small to be clickable. 

As seen in the below screenshot (from a Pixel 3a XL device)

<img src="https://user-images.githubusercontent.com/84779237/160133943-b9c8c4a3-7b24-4b5d-970d-02318bc4bb22.png" width="400px" />

**Comment by alexvanyo** [comment]
Thank you for this report, and thank you for the contribution! This was changed in the latest insets update, I'll take a look at the PR now.
