### ISSUE TITLE
how to dynamic create/delete or hide/show composable component in Jetpack Compose

### ISSUE THREAD

**Issue by chengstone** [android/compose-samples#78]
hi, android teem

thanks for your great demo,  I've learned a lot.
Something I'd like to ask you a question, just like title :
how to dynamic open/close a list(some component create/delete or hide/show in the list item) in Jetpack Compose?

I think this is a challenge using the Jetpack Compose, it feels like:
<img width="294" alt="sample" src="https://user-images.githubusercontent.com/6791799/79739601-5f17ef00-8339-11ea-81b9-c21c6beb9468.png">

excuse me for bothering you,
I appreciate your response

Thank you

**Comment by chengstone** [comment]
I solved using Toggleable, thanks very much

**Comment by DavidRajPaul** [comment]
Hi @chengstone , I am also facing issues trying to implement an ExpandableListView equivalent UI in Jetpack compose. Can you share any sample for reference on how you achieved this using Toggleable?
