### ISSUE TITLE
[Jet Chat]:  Show pop up with explicit token like @ for user mentions # for hashtags

### ISSUE THREAD

**Issue by raghunandankavi2010** [android/compose-samples#785]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is this a feature request for one of the samples?

- [X] Yes, this is a specific request related to this samples repo.

### Sample app

Jetchat

### Describe the problem

I want to tag users or mention hashtags when typing in text field. This is similar to something most chat apps have like twitter and facebook. Have used https://github.com/linkedin/Spyglass for my use case using xml layouts. 

### Describe the solution

Would love to have the solution where user can tag others or hashtags with explicit token like @ or # in textfield.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by raghunandankavi2010** [comment]
Got the idea. Implemented a raw solution for my use case.

**Comment by iRaam** [comment]
@raghunandankavi2010 Could you please post here how you implemented this feature ?

**Comment by rishiraj88** [comment]
Yes, please, @raghunandankavi2010 . We would all love to view and learn that. Thanks, @iRaam , for the request.

**Comment by DawnNguyenAhiho** [comment]
Me too, I would love to view and learn how to do that in Jetpack compose, please can you share with us @raghunandankavi2010
