### ISSUE TITLE
Kapt not working with the sample

### ISSUE THREAD

**Issue by vipulyaara** [android/compose-samples#8]
If we add the kotlin kapt plugin 

```apply plugin: 'kotlin-kapt'```

Android studio throws an error 

```e: java.lang.IllegalStateException: Backend Internal error: Exception during code generation```

This might be an issue with the new android gradle plugin. I have tried it outside the project and same error persists.

**Comment by jerryOkafor** [comment]
Currently happening to me in a new project I bootstrapped.

**Comment by vipulyaara** [comment]
Kapt is working fine now. We get the same error now if we enable data binding

`java.lang.IllegalStateException: Backend Internal error: Exception during code generation`
