### ISSUE TITLE
[Bug]: Crane lint checks fail

### ISSUE THREAD

**Issue by IanGClifton** [android/compose-samples#800]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### Is this an issue related to one of the samples?

- [X] Yes, this is a specific issue related to this samples repo.

### Sample app

Crane

### What happened?

When running `./scripts/gradlew_recursive.sh lintDebug`, lint had an error analyzing the Crane sample. The error isn't especially clear, but it seems like a bug we need to file (as in a bug with a tool or library rather than our samples). Here's the error I saw:

> Crane/app/src/androidTest/java/androidx/compose/samples/crane/details/CityMapViewTests.kt: Error: Unexpected failure during lint analysis of CityMapViewTests.kt (this is a bug in lint or one of the libraries it depends on)
> 
> Message: 'java.util.List org.jetbrains.uast.UField.getAnnotations()'
> 
> The crash seems to involve the detector dagger.lint.DaggerKotlinIssueDetector.
> You can try disabling it with something like this:
>     android {
>         lintOptions {
>             disable "JvmStaticProvidesInObjectDetector", "FieldSiteTargetOnQualifierAnnotation", "ModuleCompanionObjects", "ModuleCompanionObjectsNotInModuleParent"
>         }
>     }

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by riggaroo** [comment]
Logged https://issuetracker.google.com/232345521

**Comment by alexvanyo** [comment]
This looks like https://github.com/google/dagger/issues/3201?

Should be fixed by https://github.com/google/dagger/commit/33ba899f96083b046a987a1ad0821db8cb36d744 and updating Dagger to `2.41` or higher (latest stable is `2.42`)

It looks like Crane is currently on `2.39`.
