### ISSUE TITLE
[FR]: Create reusable workflows

### ISSUE THREAD

**Issue by arriolac** [android/compose-samples#817]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is this a feature request for one of the samples?

- [X] Yes, this is a specific request related to this samples repo.

### Sample app

Other (bug not related to sample app)

### Describe the problem

Workflows under `.github/workflows` contain duplicated configs.

### Describe the solution

GitHub provides a way to create a reusable workflow: https://docs.github.com/en/actions/using-workflows/reusing-workflows#creating-a-reusable-workflow 

### Additional context

See discussion in #814

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by riggaroo** [comment]
Reverting this commit for now - it breaks the build #824 -> doesn't look like we can reuse it in this way.
