### ISSUE TITLE
[Jetchat] Missing content descriptions

### ISSUE THREAD

**Issue by rdias002** [android/compose-samples#823]
Hi, this is my first time contributing. I was reading the code for Jetchat and found content descriptions missing in few places. (They're set to `null`)

Code lines with issue:
1. [Conversation.kt - 321](https://github.com/android/compose-samples/blob/70d1c039018d5b77c37c1dcca8207021227b6eaa/Jetchat/app/src/main/java/com/example/compose/jetchat/conversation/Conversation.kt#L321)
2. [JetDrawer.kt - 78](https://github.com/android/compose-samples/blob/main/Jetchat/app/src/main/java/com/example/compose/jetchat/components/JetchatDrawer.kt#L78)
3. [JetDrawer.kt - 83](https://github.com/android/compose-samples/blob/main/Jetchat/app/src/main/java/com/example/compose/jetchat/components/JetchatDrawer.kt#L83)
4. [JetDrawer.kt - 164](https://github.com/android/compose-samples/blob/main/Jetchat/app/src/main/java/com/example/compose/jetchat/components/JetchatDrawer.kt#L164)
5. [JumpToBottom.kt - 66](https://github.com/android/compose-samples/blob/70d1c039018d5b77c37c1dcca8207021227b6eaa/Jetchat/app/src/main/java/com/example/compose/jetchat/conversation/JumpToBottom.kt#L66)
6. [Profile.kt - 218](https://github.com/android/compose-samples/blob/70d1c039018d5b77c37c1dcca8207021227b6eaa/Jetchat/app/src/main/java/com/example/compose/jetchat/profile/Profile.kt#L218)

My plan is to create string resources and set them accordingly.

**Comment by astamato** [comment]
Hello! Thank you for creating this issue!
Keep in mind that not all content descriptions should be different than null just for the sake of it as per [ https://www.w3.org/WAI/tutorials/images/decorative/ ]. Logos and decorative images are not required to have a content description, as it provides no value for a user of TalkBack, or any screen reader.

**Comment by astamato** [comment]
Hello! Thank you for creating this issue!
Keep in mind that not all content descriptions should be different than null as per [ https://www.w3.org/WAI/tutorials/images/decorative/ ]. Logos and decorative images are not required to have a content description, as it provides no value for a user of TalkBack, or any screen reader.
