### ISSUE TITLE
Can't import

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [android/compose-samples#84]
I use canary 4.1 8, and I can't import and run this sample:

![image](https://user-images.githubusercontent.com/5357526/82158775-97581200-9892-11ea-81bd-9617fb876c23.png)

**Comment by nickbutcher** [comment]
It looks like you've imported the root folder—try importing from the `Jetnews` folder.

**Comment by AndroidDeveloperLB** [comment]
Indeed. Usually projects have the root as the one to import. 
Now I tried and it works, but something is weird:
Pressing the back key doesn't go back. It just closes, and even if I press the "up" button, it reloads the main screen. In fact it happens even on orientation change.
See:

[device-2020-05-19-191838.zip](https://github.com/android/compose-samples/files/4651772/device-2020-05-19-191838.zip)

I've also noticed that there is a navigation drawer, yet it was hard to notice because there is no "hamburger" icon. The navigation drawer forgets its state upon orientation change, and  when choosing "interest" it has tabs but no viewPager to swipe between them.

I guess it's more about Compose than how to handle apps nicely, but still... Seems you've put a lot of effort on other various things, and the purpose of Compose is mainly about UI.

**Comment by nickbutcher** [comment]
This repo is intended to be a _collection_ of samples; there's only one, Jetnews, right now but we plan to expand it.

Thanks for highlighting those issues. We are aware and working on providing advice on navigation (integrating with the system back button), configuration changes etc. Compose is still pre-alpha so not all parts are there yet.

Re the hamburger menu, this is the design, will feedback to our designer.

**Comment by AndroidDeveloperLB** [comment]
I see. I was actually quite overwhelmed by the amount of things there that I'm not familiar with.
So much that I thought it's available for a long time that people use it.
Are there any apps that use it already?
What is your suggestion about an already existing app? Especially one that doesn't even use navigation component yet (too huge and too little time for that).

**Comment by nickbutcher** [comment]
Yes, a new UI Toolkit is a large undertaking. We'll be updating our documentation, samples, codelabs etc to help you learn but need to balance this against product stability.

I can't comment on current adoption or future plans but it is a goal for Compose to work well with other Jetpack libraries so adopting those would be a good step.

**Comment by AndroidDeveloperLB** [comment]
Would it replace the current development on Android? Eventually, nobody will use XML anymore for layouts (and maybe drawable?) ? 
Is it already possible to implement everything using Compose?
Would it mean there won't be any more android-x support libraries, etc?

I actually kinda liked using XML. Got used to it quite quickly...
And I liked the division between it and normal code.

**Comment by RyanSimon** [comment]
> Would it replace the current development on Android? Eventually, nobody will use XML anymore for layouts (and maybe drawable?) ? 
> Is it already possible to implement everything using Compose?
> Would it mean there won't be any more android-x support libraries, etc?
> 
> I actually kinda liked using XML. Got used to it quite quickly...
> And I liked the division between it and normal code.
> 

I'm not a maintainer for Jetpack Compose, but having been an Android Engineer for quite some time, everything you mentioned about XML layouts is actually seen as a downside.

It's a bit out of the scope of my comment, but do a little research on declarative UI like Compose, React JS, and Swift UI. You'll find that there's a load of great reasons for Android to move in this direction.

As for answering your questions. I do believe we will continue to see people use XML and the old View based UI for some time. If only because legacy codebases will call for it, and Compose is compatible with the old way.

Arguably though, Compose is targeted at removing the need to do XML or View class based UI. So in the not so distant future, new apps would prefer starting with Compose, and never touch the old UI framework.

**Comment by AndroidDeveloperLB** [comment]
I see. I should start learning about it soon, then.
