### ISSUE TITLE
[Bug]: Crane unable to run

### ISSUE THREAD

**Issue by BraveHL** [android/compose-samples#845]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### Is this an issue related to one of the samples?

- [X] Yes, this is a specific issue related to this samples repo.

### Sample app

Crane

### What happened?

A bug happened!

Crane unable to run

![Y3}L6`4SAKHOMU$H12J2@$4](https://user-images.githubusercontent.com/22335503/173762238-5c0acacd-d288-47fd-ad96-4a326ba2ca54.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by BraveHL** [comment]
![image](https://user-images.githubusercontent.com/22335503/173762623-c4a12235-9f6f-422e-9efe-fa7979e9aed0.png)

**Comment by riggaroo** [comment]
@arriolac I think this happened as part of #836. Would you be able to provide a default that ensures people don't have to include a googleMapsKey?
