### ISSUE TITLE
@Model is deprecated

### ISSUE THREAD

**Issue by henrikhorbovyi** [android/compose-samples#92]
I know that the compose version in the project is dev11, but it would be awesome to see an alternative for the navigation with the `currentScreen` 

```
@Model
object JetnewsStatus {
    var currentScreen: Screen = Screen.Home
    val favorites = ModelList<String>()
    val selectedTopics = ModelList<String>()
}

```

**Comment by nickbutcher** [comment]
The `develop` branch is already updated to `dev12` https://github.com/android/compose-samples/blob/develop/JetNews/app/src/main/java/com/example/jetnews/ui/Status.kt#L33
