### ISSUE TITLE
[Reply] Use NavigationDrawerItem in Navigation Drawer 

### ISSUE THREAD

**Issue by JolandaVerhoef** [android/compose-samples#936]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is this a feature request for one of the samples?

- [X] Yes, this is a specific request related to this samples repo.

### Sample app

Reply

### Describe the problem

There's a TODO in code:
`remove custom nav drawer content positioning when NavDrawer component supports it. ticket : b/232495216`

That bug has been fixed, and by now you can use NavigationHeaderItem as well. 

### Describe the solution

Please update the sample to include this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Gurupreet** [comment]
Hi, Thanks for raising it. The bug has been fixed but will be part of material3-alpha17, which is yet to be released. When sample will be updated with latest version and above TODO will be removed.
