### ISSUE TITLE
This is required? I don't see any difference without

### ISSUE THREAD

**Issue by DavideSorcelli** [android/compose-samples#943]
https://github.com/android/compose-samples/blob/98c35794674855c51a6ce32728fa9fed9b87ef7e/Reply/app/src/main/java/com/example/reply/ui/components/ReplyAppBars.kt#L111

**Comment by Gurupreet** [comment]
Hi, `Modifier.weight(1f)` here make sure the text content takes the maximum space in all type of screen sizes and icons is pushed towards the end always.
