### ISSUE TITLE
[All]: Rename "roboelectric" to "robolectric" in toml files

### ISSUE THREAD

**Issue by JoseAlcerreca** [android/compose-samples#963]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### Is this an issue related to one of the samples?

- [X] Yes, this is a specific issue related to this samples repo.

### Sample app

Other (bug not related to sample app)

### What happened?

this template is way too complex for this bug XD

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bentrengrove** [comment]
Fixed in #967
