### ISSUE TITLE
[Reply]: Using Flow like LiveData to update UiState

### ISSUE THREAD

**Issue by ErfanSn** [android/compose-samples#977]
What is the need when we can use the power of intermediaries flow and directly convert data to Ui State?
It will be easier to combine different data in the future.

https://github.com/android/compose-samples/blob/5bc3451b11f9aae111b8a6dca0199a317c997a2b/Reply/app/src/main/java/com/example/reply/ui/ReplyHomeViewModel.kt#L38

**Comment by ErfanSn** [comment]
> Could I pick up this issue?

I am waiting for a response from the maintainer of the Replay project until I send PR for this.

**Comment by Aldikitta** [comment]
> > Could I pick up this issue?
> 
> I am waiting for a response from the maintainer of the Reply project until I send PR for this.

Can i see how your PR version for this reply project?

**Comment by Gurupreet** [comment]
Hi @ErfanSn since for this sample we are manually changing some UI state depending on large screen/fold states and sample requires only one data source for now. I will update it if there is need for showcasing intermediaries flows. Thanks for suggestions.
