### ISSUE TITLE
Accessibility issue with compose samples 

### ISSUE THREAD

**Issue by VytasYankis** [android/compose-samples#978]
Hi,
I'm developing Android application using Jetpack Compose and it has the same issue as all 8 sample apps from [https://github.com/android/compose-samples](https://www.google.com/url?q=https://github.com/android/compose-samples&sa=D&source=buganizer&usg=AOvVaw1N8Xz82mxj_P5RsbhchaQI) (downloaded at 2022-09-21).

Google's cloud-based app testing( [firebase.google.com](http://firebase.google.com/) , [play.google.com/console](http://play.google.com/console)) founds issues with "Content labeling"(Accessibility), problem that it says problem is at "android:id/content/ComposeView[0]/AndroidComposeView[0]", not all paths are the same for sample apps, but all paths ends with "AndroidComposeView[0]"

Is there a way to set a label for this item?
p.s. attached screenshots from firebase console

Android Studio Build: #AI-213.7172.25.2113.9014738, built on August 31, 2022
![Crane](https://user-images.githubusercontent.com/59872345/191664801-708a426d-5f87-4150-8350-80d1a01716e5.png)
![Jetcaster](https://user-images.githubusercontent.com/59872345/191664806-722e9896-0275-4e2c-a861-7d846ee67b3f.png)
![Jetchat](https://user-images.githubusercontent.com/59872345/191664808-975ad809-74be-43ba-986c-d31f1d7d7751.png)
![JetNews](https://user-images.githubusercontent.com/59872345/191664810-b78d95fc-29ef-43e0-b592-360ed9a24094.png)
![Jetsnack](https://user-images.githubusercontent.com/59872345/191664812-01010185-b08b-4894-8ced-708ea0fb952d.png)
![Jetsurvey](https://user-images.githubusercontent.com/59872345/191664814-06f09a15-ae92-46f4-8196-44a177a49d2d.png)
![Owl](https://user-images.githubusercontent.com/59872345/191664815-76c3faa4-1c02-4077-86c8-d2ec0fd1b611.png)
![Reply](https://user-images.githubusercontent.com/59872345/191664816-478df2a7-7004-4596-a013-3482385b595d.png)

**Comment by JolandaVerhoef** [comment]
Hi! This unfortunately isn't a problem solely for our Compose samples, but a wider issue. We're tracking it at https://issuetracker.google.com/220801884 and are working to get it resolved. I'll close this issue, but feel free to follow progress on that bug instead! You can also upvote that bug if you personally are affected by it.
